//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.09.18 at 02:35:45 PM BST
//

package net.sf.mpxj.primavera.schema

import java.util.Date
import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlSchemaType
import javax.xml.bind.annotation.XmlType
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter

/**
 *
 * Java class for ActivityStepUpdateType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ActivityStepUpdateType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="ActivityObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="ActivityStepObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="ApprovalDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="ApprovalUserName" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ApprovalUserObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="ChangeSetObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="HeldDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="OverridePercentComplete" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="0.0"/>
 * &lt;maxInclusive value="100.0"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="OverrideStepName" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="120"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="PendingPercentComplete" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="0.0"/>
 * &lt;maxInclusive value="100.0"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="PendingStepName" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="120"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ProjectObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="RequestUserObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Status" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Pending"/>
 * &lt;enumeration value="Held"/>
 * &lt;enumeration value="Approved"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActivityStepUpdateType", propOrder = {
    "activityObjectId",
    "activityStepObjectId",
    "approvalDate",
    "approvalUserName",
    "approvalUserObjectId",
    "changeSetObjectId",
    "date",
    "heldDate",
    "overridePercentComplete",
    "overrideStepName",
    "pendingPercentComplete",
    "pendingStepName",
    "projectObjectId",
    "requestUserObjectId",
    "status"
})
class ActivityStepUpdateType {

    /**
     * Gets the value of the activityObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the activityObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ActivityObjectId")
    var activityObjectId: Integer
    /**
     * Gets the value of the activityStepObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the activityStepObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ActivityStepObjectId")
    var activityStepObjectId: Integer
    /**
     * Gets the value of the approvalDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the approvalDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ApprovalDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var approvalDate: Date
    /**
     * Gets the value of the approvalUserName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the approvalUserName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ApprovalUserName")
    var approvalUserName: String
    /**
     * Gets the value of the approvalUserObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the approvalUserObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ApprovalUserObjectId", nillable = true)
    var approvalUserObjectId: Integer
    /**
     * Gets the value of the changeSetObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the changeSetObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ChangeSetObjectId")
    var changeSetObjectId: Integer
    /**
     * Gets the value of the date property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the date property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Date", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var date: Date
    /**
     * Gets the value of the heldDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the heldDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "HeldDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var heldDate: Date
    /**
     * Gets the value of the overridePercentComplete property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the overridePercentComplete property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "OverridePercentComplete", nillable = true)
    var overridePercentComplete: Double
    /**
     * Gets the value of the overrideStepName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the overrideStepName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "OverrideStepName")
    var overrideStepName: String
    /**
     * Gets the value of the pendingPercentComplete property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the pendingPercentComplete property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "PendingPercentComplete", nillable = true)
    var pendingPercentComplete: Double
    /**
     * Gets the value of the pendingStepName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the pendingStepName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PendingStepName")
    var pendingStepName: String
    /**
     * Gets the value of the projectObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the projectObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ProjectObjectId")
    var projectObjectId: Integer
    /**
     * Gets the value of the requestUserObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the requestUserObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "RequestUserObjectId", nillable = true)
    var requestUserObjectId: Integer
    /**
     * Gets the value of the status property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the status property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Status")
    var status: String

}
