//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.09.18 at 02:35:45 PM BST
//

package net.sf.mpxj.primavera.schema

import java.util.Date
import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlSchemaType
import javax.xml.bind.annotation.XmlType
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter

/**
 *
 * Java class for ActivityPeriodActualType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ActivityPeriodActualType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="ActivityObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="ActualExpenseCost" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 * &lt;element name="ActualLaborCost" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 * &lt;element name="ActualLaborUnits" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 * &lt;element name="ActualMaterialCost" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 * &lt;element name="ActualNonLaborCost" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 * &lt;element name="ActualNonLaborUnits" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 * &lt;element name="CreateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="CreateUser" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="EarnedValueCost" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 * &lt;element name="EarnedValueLaborUnits" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 * &lt;element name="FinancialPeriodObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="IsBaseline" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="IsTemplate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="LastUpdateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="LastUpdateUser" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="PlannedValueCost" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 * &lt;element name="PlannedValueLaborUnits" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 * &lt;element name="ProjectObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="WBSObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActivityPeriodActualType", propOrder = {
    "activityObjectId",
    "actualExpenseCost",
    "actualLaborCost",
    "actualLaborUnits",
    "actualMaterialCost",
    "actualNonLaborCost",
    "actualNonLaborUnits",
    "createDate",
    "createUser",
    "earnedValueCost",
    "earnedValueLaborUnits",
    "financialPeriodObjectId",
    "isBaseline",
    "isTemplate",
    "lastUpdateDate",
    "lastUpdateUser",
    "plannedValueCost",
    "plannedValueLaborUnits",
    "projectObjectId",
    "wbsObjectId"
})
class ActivityPeriodActualType {

    /**
     * Gets the value of the activityObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the activityObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ActivityObjectId")
    var activityObjectId: Integer
    /**
     * Gets the value of the actualExpenseCost property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the actualExpenseCost property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "ActualExpenseCost", nillable = true)
    var actualExpenseCost: Double
    /**
     * Gets the value of the actualLaborCost property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the actualLaborCost property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "ActualLaborCost", nillable = true)
    var actualLaborCost: Double
    /**
     * Gets the value of the actualLaborUnits property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the actualLaborUnits property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "ActualLaborUnits", nillable = true)
    var actualLaborUnits: Double
    /**
     * Gets the value of the actualMaterialCost property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the actualMaterialCost property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "ActualMaterialCost", nillable = true)
    var actualMaterialCost: Double
    /**
     * Gets the value of the actualNonLaborCost property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the actualNonLaborCost property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "ActualNonLaborCost", nillable = true)
    var actualNonLaborCost: Double
    /**
     * Gets the value of the actualNonLaborUnits property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the actualNonLaborUnits property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "ActualNonLaborUnits", nillable = true)
    var actualNonLaborUnits: Double
    /**
     * Gets the value of the createDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the createDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "CreateDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var createDate: Date
    /**
     * Gets the value of the createUser property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the createUser property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "CreateUser")
    var createUser: String
    /**
     * Gets the value of the earnedValueCost property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the earnedValueCost property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "EarnedValueCost", nillable = true)
    var earnedValueCost: Double
    /**
     * Gets the value of the earnedValueLaborUnits property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the earnedValueLaborUnits property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "EarnedValueLaborUnits", nillable = true)
    var earnedValueLaborUnits: Double
    /**
     * Gets the value of the financialPeriodObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the financialPeriodObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "FinancialPeriodObjectId")
    var financialPeriodObjectId: Integer
    /**
     * Gets the value of the isBaseline property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the isBaseline property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "IsBaseline")
    var isIsBaseline: Boolean
    /**
     * Gets the value of the isTemplate property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the isTemplate property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "IsTemplate")
    var isIsTemplate: Boolean
    /**
     * Gets the value of the lastUpdateDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the lastUpdateDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "LastUpdateDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var lastUpdateDate: Date
    /**
     * Gets the value of the lastUpdateUser property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the lastUpdateUser property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "LastUpdateUser")
    var lastUpdateUser: String
    /**
     * Gets the value of the plannedValueCost property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the plannedValueCost property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "PlannedValueCost", nillable = true)
    var plannedValueCost: Double
    /**
     * Gets the value of the plannedValueLaborUnits property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the plannedValueLaborUnits property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "PlannedValueLaborUnits", nillable = true)
    var plannedValueLaborUnits: Double
    /**
     * Gets the value of the projectObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the projectObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ProjectObjectId")
    var projectObjectId: Integer
    /**
     * Gets the value of the wbsObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the wbsObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "WBSObjectId", nillable = true)
    var wbsObjectId: Integer

}
