//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.09.18 at 02:35:45 PM BST
//

package net.sf.mpxj.primavera.schema

import java.util.ArrayList
import java.util.Date
import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlSchemaType
import javax.xml.bind.annotation.XmlType
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter

/**
 *
 * Java class for DocumentType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DocumentType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="Author" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ContentRepositoryDocumentInternalId" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="4000"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="CreateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="CreateUser" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="Deliverable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="DocumentCategoryName" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="DocumentCategoryObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="DocumentStatusCodeName" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="36"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="DocumentStatusCodeObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="DocumentType" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Non-Collaboration Document"/>
 * &lt;enumeration value="Collaboration Document"/>
 * &lt;enumeration value="Repository Document"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="GUID" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;pattern value="\{[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\}|"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="IsBaseline" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="IsTemplate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="LastUpdateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="LastUpdateUser" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="ParentObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="PrivateLocation" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ProjectId" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="40"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ProjectObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="PublicLocation" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ReferenceNumber" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="32"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ResourceId" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="20"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ResourceName" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ResourceObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="RevisionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="SequenceNumber" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Title" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="120"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="Version" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="20"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="UDF" type="{http://xmlns.oracle.com/Primavera/P6/V17.7/API/BusinessObjects}UDFAssignmentType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentType", propOrder = {
    "author",
    "contentRepositoryDocumentInternalId",
    "createDate",
    "createUser",
    "deliverable",
    "description",
    "documentCategoryName",
    "documentCategoryObjectId",
    "documentStatusCodeName",
    "documentStatusCodeObjectId",
    "documentType",
    "guid",
    "isBaseline",
    "isTemplate",
    "lastUpdateDate",
    "lastUpdateUser",
    "objectId",
    "parentObjectId",
    "privateLocation",
    "projectId",
    "projectObjectId",
    "publicLocation",
    "referenceNumber",
    "resourceId",
    "resourceName",
    "resourceObjectId",
    "revisionDate",
    "sequenceNumber",
    "title",
    "version",
    "udf"
})
class DocumentType {

    /**
     * Gets the value of the author property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the author property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Author")
    var author: String
    /**
     * Gets the value of the contentRepositoryDocumentInternalId property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the contentRepositoryDocumentInternalId property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ContentRepositoryDocumentInternalId")
    var contentRepositoryDocumentInternalId: String
    /**
     * Gets the value of the createDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the createDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "CreateDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var createDate: Date
    /**
     * Gets the value of the createUser property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the createUser property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "CreateUser")
    var createUser: String
    /**
     * Gets the value of the deliverable property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the deliverable property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "Deliverable")
    var isDeliverable: Boolean
    /**
     * Gets the value of the description property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the description property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Description")
    var description: String
    /**
     * Gets the value of the documentCategoryName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the documentCategoryName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "DocumentCategoryName")
    var documentCategoryName: String
    /**
     * Gets the value of the documentCategoryObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the documentCategoryObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "DocumentCategoryObjectId", nillable = true)
    var documentCategoryObjectId: Integer
    /**
     * Gets the value of the documentStatusCodeName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the documentStatusCodeName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "DocumentStatusCodeName")
    var documentStatusCodeName: String
    /**
     * Gets the value of the documentStatusCodeObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the documentStatusCodeObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "DocumentStatusCodeObjectId", nillable = true)
    var documentStatusCodeObjectId: Integer
    /**
     * Gets the value of the documentType property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the documentType property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "DocumentType")
    var documentType: String
    /**
     * Gets the value of the guid property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the guid property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "GUID")
    var guid: String
    /**
     * Gets the value of the isBaseline property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the isBaseline property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "IsBaseline", nillable = true)
    var isIsBaseline: Boolean
    /**
     * Gets the value of the isTemplate property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the isTemplate property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "IsTemplate")
    var isIsTemplate: Boolean
    /**
     * Gets the value of the lastUpdateDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the lastUpdateDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "LastUpdateDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var lastUpdateDate: Date
    /**
     * Gets the value of the lastUpdateUser property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the lastUpdateUser property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "LastUpdateUser")
    var lastUpdateUser: String
    /**
     * Gets the value of the objectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the objectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ObjectId")
    var objectId: Integer
    /**
     * Gets the value of the parentObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the parentObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ParentObjectId", nillable = true)
    var parentObjectId: Integer
    /**
     * Gets the value of the privateLocation property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the privateLocation property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PrivateLocation")
    var privateLocation: String
    /**
     * Gets the value of the projectId property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the projectId property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ProjectId")
    var projectId: String
    /**
     * Gets the value of the projectObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the projectObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ProjectObjectId", nillable = true)
    var projectObjectId: Integer
    /**
     * Gets the value of the publicLocation property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the publicLocation property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PublicLocation")
    var publicLocation: String
    /**
     * Gets the value of the referenceNumber property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the referenceNumber property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ReferenceNumber")
    var referenceNumber: String
    /**
     * Gets the value of the resourceId property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the resourceId property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ResourceId")
    var resourceId: String
    /**
     * Gets the value of the resourceName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the resourceName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ResourceName")
    var resourceName: String
    /**
     * Gets the value of the resourceObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the resourceObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ResourceObjectId", nillable = true)
    var resourceObjectId: Integer
    /**
     * Gets the value of the revisionDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the revisionDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "RevisionDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var revisionDate: Date
    /**
     * Gets the value of the sequenceNumber property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the sequenceNumber property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "SequenceNumber")
    var sequenceNumber: Integer
    /**
     * Gets the value of the title property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the title property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Title")
    var title: String
    /**
     * Gets the value of the version property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the version property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Version")
    var version: String
    @XmlElement(name = "UDF")
    protected var udf: List<UDFAssignmentType>? = null

    /**
     * Gets the value of the udf property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the udf property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getUDF().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [UDFAssignmentType]
     *
     *
     */
    fun getUDF(): List<UDFAssignmentType> {
        if (udf == null) {
            udf = ArrayList<UDFAssignmentType>()
        }
        return this.udf
    }

}
