//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.09.18 at 02:35:45 PM BST
//

package net.sf.mpxj.primavera.schema

import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlType

/**
 *
 * Java class for GlobalReplaceType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="GlobalReplaceType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="AllProjects" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="GlobalReplaceData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="GlobalReplaceName" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="GreplaceObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="ProjectIdName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="ProjectIds" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="ReplaceFieldNameOne" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="SearchCriteria" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="SubjectAreaType" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="UserObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GlobalReplaceType", propOrder = {
    "allProjects",
    "globalReplaceData",
    "globalReplaceName",
    "greplaceObjectId",
    "projectIdName",
    "projectIds",
    "replaceFieldNameOne",
    "searchCriteria",
    "subjectAreaType",
    "userObjectId"
})
class GlobalReplaceType {

    /**
     * Gets the value of the allProjects property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the allProjects property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "AllProjects", nillable = true)
    var isAllProjects: Boolean
    /**
     * Gets the value of the globalReplaceData property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the globalReplaceData property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "GlobalReplaceData")
    var globalReplaceData: String
    /**
     * Gets the value of the globalReplaceName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the globalReplaceName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "GlobalReplaceName")
    var globalReplaceName: String
    /**
     * Gets the value of the greplaceObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the greplaceObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "GreplaceObjectId")
    var greplaceObjectId: Integer
    /**
     * Gets the value of the projectIdName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the projectIdName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ProjectIdName")
    var projectIdName: String
    /**
     * Gets the value of the projectIds property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the projectIds property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ProjectIds")
    var projectIds: String
    /**
     * Gets the value of the replaceFieldNameOne property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the replaceFieldNameOne property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ReplaceFieldNameOne")
    var replaceFieldNameOne: String
    /**
     * Gets the value of the searchCriteria property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the searchCriteria property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "SearchCriteria")
    var searchCriteria: String
    /**
     * Gets the value of the subjectAreaType property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the subjectAreaType property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "SubjectAreaType")
    var subjectAreaType: String
    /**
     * Gets the value of the userObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the userObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "UserObjectId", nillable = true)
    var userObjectId: Integer

}
