//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.09.18 at 02:35:45 PM BST
//

package net.sf.mpxj.primavera.schema

import java.util.Date
import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlSchemaType
import javax.xml.bind.annotation.XmlType
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter

/**
 *
 * Java class for JobServiceType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="JobServiceType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="ExportFilePath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="ImportXMLByte" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="JobData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="JobDataX" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="JobRecurringType" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value=""/>
 * &lt;enumeration value="Enabled"/>
 * &lt;enumeration value="Disabled"/>
 * &lt;enumeration value="WebASAP"/>
 * &lt;enumeration value="None"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="JobStatus" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Pending"/>
 * &lt;enumeration value="Running"/>
 * &lt;enumeration value="Complete"/>
 * &lt;enumeration value="Failed"/>
 * &lt;enumeration value="Cancelled"/>
 * &lt;enumeration value="Delegated"/>
 * &lt;enumeration value="Completed With Errors"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="JobType" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Schedule"/>
 * &lt;enumeration value="Summarize"/>
 * &lt;enumeration value="Apply Actuals"/>
 * &lt;enumeration value="Store Period Performance"/>
 * &lt;enumeration value="Sync Actual This Period"/>
 * &lt;enumeration value="Level"/>
 * &lt;enumeration value="Recalculate Assignment Costs"/>
 * &lt;enumeration value="Send To Unifier"/>
 * &lt;enumeration value="Update Baseline"/>
 * &lt;enumeration value="Import Project"/>
 * &lt;enumeration value="Schedule Check"/>
 * &lt;enumeration value="Export Project"/>
 * &lt;enumeration value="Project CBS Service"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="JobTypeKey" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="LastRunDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="Name" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="PlfDirName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JobServiceType", propOrder = {
    "exportFilePath",
    "fileName",
    "importXMLByte",
    "jobData",
    "jobDataX",
    "jobRecurringType",
    "jobStatus",
    "jobType",
    "jobTypeKey",
    "lastRunDate",
    "name",
    "objectId",
    "plfDirName",
    "userId"
})
class JobServiceType {

    /**
     * Gets the value of the exportFilePath property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the exportFilePath property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ExportFilePath")
    var exportFilePath: String
    /**
     * Gets the value of the fileName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the fileName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "FileName")
    var fileName: String
    /**
     * Gets the value of the importXMLByte property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the importXMLByte property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ImportXMLByte")
    var importXMLByte: String
    /**
     * Gets the value of the jobData property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the jobData property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "JobData")
    var jobData: String
    /**
     * Gets the value of the jobDataX property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the jobDataX property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "JobDataX")
    var jobDataX: String
    /**
     * Gets the value of the jobRecurringType property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the jobRecurringType property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "JobRecurringType")
    var jobRecurringType: String
    /**
     * Gets the value of the jobStatus property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the jobStatus property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "JobStatus")
    var jobStatus: String
    /**
     * Gets the value of the jobType property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the jobType property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "JobType")
    var jobType: String
    /**
     * Gets the value of the jobTypeKey property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the jobTypeKey property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "JobTypeKey")
    var jobTypeKey: String
    /**
     * Gets the value of the lastRunDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the lastRunDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "LastRunDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var lastRunDate: Date
    /**
     * Gets the value of the name property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the name property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Name")
    var name: String
    /**
     * Gets the value of the objectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the objectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ObjectId", nillable = true)
    var objectId: Integer
    /**
     * Gets the value of the plfDirName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the plfDirName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PlfDirName")
    var plfDirName: String
    /**
     * Gets the value of the userId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the userId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "UserId", nillable = true)
    var userId: Integer

}
