//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.09.18 at 02:35:45 PM BST
//

package net.sf.mpxj.primavera.schema

import java.util.Date
import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlSchemaType
import javax.xml.bind.annotation.XmlType
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter

/**
 *
 * Java class for ProjectResourceQuantityType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ProjectResourceQuantityType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="CommittedFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="CreateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="CreateUser" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="FinancialPeriod1ObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="FinancialPeriod1Quantity" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="0.0"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="FinancialPeriod2ObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="FinancialPeriod2Quantity" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="0.0"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="IsBaseline" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="IsTemplate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="LastUpdateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="LastUpdateUser" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="MonthStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="ProjectObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="ProjectResourceObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Quantity" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="0.0"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ResourceObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="RoleObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="WBSObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="WeekStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProjectResourceQuantityType", propOrder = {
    "committedFlag",
    "createDate",
    "createUser",
    "financialPeriod1ObjectId",
    "financialPeriod1Quantity",
    "financialPeriod2ObjectId",
    "financialPeriod2Quantity",
    "isBaseline",
    "isTemplate",
    "lastUpdateDate",
    "lastUpdateUser",
    "monthStartDate",
    "projectObjectId",
    "projectResourceObjectId",
    "quantity",
    "resourceObjectId",
    "roleObjectId",
    "wbsObjectId",
    "weekStartDate"
})
class ProjectResourceQuantityType {

    /**
     * Gets the value of the committedFlag property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the committedFlag property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "CommittedFlag", nillable = true)
    var isCommittedFlag: Boolean
    /**
     * Gets the value of the createDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the createDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "CreateDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var createDate: Date
    /**
     * Gets the value of the createUser property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the createUser property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "CreateUser")
    var createUser: String
    /**
     * Gets the value of the financialPeriod1ObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the financialPeriod1ObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "FinancialPeriod1ObjectId", nillable = true)
    var financialPeriod1ObjectId: Integer
    /**
     * Gets the value of the financialPeriod1Quantity property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the financialPeriod1Quantity property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "FinancialPeriod1Quantity", nillable = true)
    var financialPeriod1Quantity: Double
    /**
     * Gets the value of the financialPeriod2ObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the financialPeriod2ObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "FinancialPeriod2ObjectId", nillable = true)
    var financialPeriod2ObjectId: Integer
    /**
     * Gets the value of the financialPeriod2Quantity property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the financialPeriod2Quantity property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "FinancialPeriod2Quantity", nillable = true)
    var financialPeriod2Quantity: Double
    /**
     * Gets the value of the isBaseline property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the isBaseline property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "IsBaseline")
    var isIsBaseline: Boolean
    /**
     * Gets the value of the isTemplate property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the isTemplate property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "IsTemplate")
    var isIsTemplate: Boolean
    /**
     * Gets the value of the lastUpdateDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the lastUpdateDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "LastUpdateDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var lastUpdateDate: Date
    /**
     * Gets the value of the lastUpdateUser property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the lastUpdateUser property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "LastUpdateUser")
    var lastUpdateUser: String
    /**
     * Gets the value of the monthStartDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the monthStartDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "MonthStartDate", type = String::class)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var monthStartDate: Date
    /**
     * Gets the value of the projectObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the projectObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ProjectObjectId", nillable = true)
    var projectObjectId: Integer
    /**
     * Gets the value of the projectResourceObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the projectResourceObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ProjectResourceObjectId")
    var projectResourceObjectId: Integer
    /**
     * Gets the value of the quantity property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the quantity property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "Quantity")
    var quantity: Double
    /**
     * Gets the value of the resourceObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the resourceObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ResourceObjectId", nillable = true)
    var resourceObjectId: Integer
    /**
     * Gets the value of the roleObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the roleObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "RoleObjectId", nillable = true)
    var roleObjectId: Integer
    /**
     * Gets the value of the wbsObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the wbsObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "WBSObjectId", nillable = true)
    var wbsObjectId: Integer
    /**
     * Gets the value of the weekStartDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the weekStartDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "WeekStartDate", type = String::class)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var weekStartDate: Date

}
