//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.09.18 at 02:35:45 PM BST
//

package net.sf.mpxj.primavera.schema

import java.util.ArrayList
import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlAttribute
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlType

/**
 *
 * Java class for ProjectListType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ProjectListType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="Project" maxOccurs="unbounded">
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 * &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 * &lt;element name="BaselineProject" maxOccurs="unbounded" minOccurs="0">
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="BaselineTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 * &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 * &lt;/sequence>
 * &lt;attribute name="ObjectId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * &lt;/element>
 * &lt;/sequence>
 * &lt;attribute name="ObjectId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * &lt;/element>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProjectListType", propOrder = {
    "project"
})
class ProjectListType {

    @XmlElement(name = "Project", required = true)
    protected var project: List<ProjectListType.Project>? = null

    /**
     * Gets the value of the project property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the project property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getProject().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [ProjectListType.Project]
     *
     *
     */
    fun getProject(): List<ProjectListType.Project> {
        if (project == null) {
            project = ArrayList<ProjectListType.Project>()
        }
        return this.project
    }

    /**
     *
     * Java class for anonymous complex type.
     *
     *
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     * &lt;complexContent>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     * &lt;sequence>
     * &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     * &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     * &lt;element name="BaselineProject" maxOccurs="unbounded" minOccurs="0">
     * &lt;complexType>
     * &lt;complexContent>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     * &lt;sequence>
     * &lt;element name="BaselineTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     * &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     * &lt;/sequence>
     * &lt;attribute name="ObjectId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     * &lt;/restriction>
     * &lt;/complexContent>
     * &lt;/complexType>
     * &lt;/element>
     * &lt;/sequence>
     * &lt;attribute name="ObjectId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     * &lt;/restriction>
     * &lt;/complexContent>
     * &lt;/complexType>
    </pre> *
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "name",
        "baselineProject"
    })
    class Project {

        /**
         * Gets the value of the id property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the id property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(name = "Id", required = true)
        var id: String
        /**
         * Gets the value of the name property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the name property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(name = "Name", required = true)
        var name: String
        @XmlElement(name = "BaselineProject")
        protected var baselineProject: List<ProjectListType.Project.BaselineProject>? = null
        /**
         * Gets the value of the objectId property.
         *
         */
        /**
         * Sets the value of the objectId property.
         *
         */
        @XmlAttribute(name = "ObjectId", required = true)
        var objectId: Int = 0

        /**
         * Gets the value of the baselineProject property.
         *
         *
         *
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the baselineProject property.
         *
         *
         *
         * For example, to add a new item, do as follows:
         * <pre>
         * getBaselineProject().add(newItem);
        </pre> *
         *
         *
         *
         *
         * Objects of the following type(s) are allowed in the list
         * [ProjectListType.Project.BaselineProject]
         *
         *
         */
        fun getBaselineProject(): List<ProjectListType.Project.BaselineProject> {
            if (baselineProject == null) {
                baselineProject = ArrayList<ProjectListType.Project.BaselineProject>()
            }
            return this.baselineProject
        }

        /**
         *
         * Java class for anonymous complex type.
         *
         *
         * The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         * &lt;complexContent>
         * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         * &lt;sequence>
         * &lt;element name="BaselineTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         * &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         * &lt;/sequence>
         * &lt;attribute name="ObjectId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         * &lt;/restriction>
         * &lt;/complexContent>
         * &lt;/complexType>
        </pre> *
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "baselineTypeName",
            "name"
        })
        class BaselineProject {

            /**
             * Gets the value of the baselineTypeName property.
             *
             * @return
             * possible object is
             * [String]
             */
            /**
             * Sets the value of the baselineTypeName property.
             *
             * @param value
             * allowed object is
             * [String]
             */
            @XmlElement(name = "BaselineTypeName", required = true)
            var baselineTypeName: String
            /**
             * Gets the value of the name property.
             *
             * @return
             * possible object is
             * [String]
             */
            /**
             * Sets the value of the name property.
             *
             * @param value
             * allowed object is
             * [String]
             */
            @XmlElement(name = "Name", required = true)
            var name: String
            /**
             * Gets the value of the objectId property.
             *
             */
            /**
             * Sets the value of the objectId property.
             *
             */
            @XmlAttribute(name = "ObjectId", required = true)
            var objectId: Int = 0

        }

    }

}
