//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.09.18 at 02:35:45 PM BST
//

package net.sf.mpxj.primavera.schema

import java.util.Date
import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlSchemaType
import javax.xml.bind.annotation.XmlType
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter

/**
 *
 * Java class for ProjectThresholdType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ProjectThresholdType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="CreateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="CreateUser" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="DetailToMonitor" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Activity"/>
 * &lt;enumeration value="WBS"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="FromDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="FromDateExpression" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="50"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="IsBaseline" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="IsTemplate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="IssuePriority" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Top"/>
 * &lt;enumeration value="High"/>
 * &lt;enumeration value="Normal"/>
 * &lt;enumeration value="Low"/>
 * &lt;enumeration value="Lowest"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="LastUpdateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="LastUpdateUser" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="LowerThreshold" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="-9.99999999999999E12"/>
 * &lt;maxInclusive value="9.99999999999999E12"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="OBSObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="ObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="ProjectId" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="40"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ProjectObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Status" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Enabled"/>
 * &lt;enumeration value="Disabled"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ThresholdParameterObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="ToDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="ToDateExpression" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="50"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="UpperThreshold" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="-9.99999999999999E12"/>
 * &lt;maxInclusive value="9.99999999999999E12"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="WBSCode" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="40"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="WBSName" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="WBSObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProjectThresholdType", propOrder = {
    "createDate",
    "createUser",
    "detailToMonitor",
    "fromDate",
    "fromDateExpression",
    "isBaseline",
    "isTemplate",
    "issuePriority",
    "lastUpdateDate",
    "lastUpdateUser",
    "lowerThreshold",
    "obsObjectId",
    "objectId",
    "projectId",
    "projectObjectId",
    "status",
    "thresholdParameterObjectId",
    "toDate",
    "toDateExpression",
    "upperThreshold",
    "wbsCode",
    "wbsName",
    "wbsObjectId"
})
class ProjectThresholdType {

    /**
     * Gets the value of the createDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the createDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "CreateDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var createDate: Date
    /**
     * Gets the value of the createUser property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the createUser property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "CreateUser")
    var createUser: String
    /**
     * Gets the value of the detailToMonitor property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the detailToMonitor property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "DetailToMonitor")
    var detailToMonitor: String
    /**
     * Gets the value of the fromDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the fromDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "FromDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var fromDate: Date
    /**
     * Gets the value of the fromDateExpression property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the fromDateExpression property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "FromDateExpression")
    var fromDateExpression: String
    /**
     * Gets the value of the isBaseline property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the isBaseline property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "IsBaseline")
    var isIsBaseline: Boolean
    /**
     * Gets the value of the isTemplate property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the isTemplate property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "IsTemplate")
    var isIsTemplate: Boolean
    /**
     * Gets the value of the issuePriority property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the issuePriority property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "IssuePriority")
    var issuePriority: String
    /**
     * Gets the value of the lastUpdateDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the lastUpdateDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "LastUpdateDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var lastUpdateDate: Date
    /**
     * Gets the value of the lastUpdateUser property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the lastUpdateUser property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "LastUpdateUser")
    var lastUpdateUser: String
    /**
     * Gets the value of the lowerThreshold property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the lowerThreshold property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "LowerThreshold", nillable = true)
    var lowerThreshold: Double
    /**
     * Gets the value of the obsObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the obsObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "OBSObjectId")
    var obsObjectId: Integer
    /**
     * Gets the value of the objectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the objectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ObjectId")
    var objectId: Integer
    /**
     * Gets the value of the projectId property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the projectId property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ProjectId")
    var projectId: String
    /**
     * Gets the value of the projectObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the projectObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ProjectObjectId")
    var projectObjectId: Integer
    /**
     * Gets the value of the status property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the status property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Status")
    var status: String
    /**
     * Gets the value of the thresholdParameterObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the thresholdParameterObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ThresholdParameterObjectId")
    var thresholdParameterObjectId: Integer
    /**
     * Gets the value of the toDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the toDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ToDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var toDate: Date
    /**
     * Gets the value of the toDateExpression property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the toDateExpression property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ToDateExpression")
    var toDateExpression: String
    /**
     * Gets the value of the upperThreshold property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the upperThreshold property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "UpperThreshold", nillable = true)
    var upperThreshold: Double
    /**
     * Gets the value of the wbsCode property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the wbsCode property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "WBSCode")
    var wbsCode: String
    /**
     * Gets the value of the wbsName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the wbsName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "WBSName")
    var wbsName: String
    /**
     * Gets the value of the wbsObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the wbsObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "WBSObjectId", nillable = true)
    var wbsObjectId: Integer

}
