//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.09.18 at 02:35:45 PM BST
//

package net.sf.mpxj.primavera.schema

import java.util.ArrayList
import java.util.Date
import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlSchemaType
import javax.xml.bind.annotation.XmlType
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter

/**
 *
 * Java class for ProjectIssueType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ProjectIssueType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="ActivityId" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="40"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ActivityName" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="120"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ActivityObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="ActualValue" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 * &lt;element name="CreateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="CreateUser" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="DateIdentified" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="IdentifiedBy" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="IsBaseline" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="IsTemplate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="LastUpdateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="LastUpdateUser" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="LowerThreshold" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="-9.99999999999999E12"/>
 * &lt;maxInclusive value="9.99999999999999E12"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="Name" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="OBSName" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="OBSObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="ObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Priority" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Top"/>
 * &lt;enumeration value="High"/>
 * &lt;enumeration value="Normal"/>
 * &lt;enumeration value="Low"/>
 * &lt;enumeration value="Lowest"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ProjectId" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="40"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ProjectName" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ProjectObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="ProjectThresholdObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="RawTextNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="ResolutionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="ResourceId" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="20"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ResourceName" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ResourceObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Status" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Open"/>
 * &lt;enumeration value="On Hold"/>
 * &lt;enumeration value="Closed"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ThresholdParameterObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="UpperThreshold" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="-9.99999999999999E12"/>
 * &lt;maxInclusive value="9.99999999999999E12"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="WBSCode" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="40"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="WBSName" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="WBSObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="UDF" type="{http://xmlns.oracle.com/Primavera/P6/V17.7/API/BusinessObjects}UDFAssignmentType" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProjectIssueType", propOrder = {
    "activityId",
    "activityName",
    "activityObjectId",
    "actualValue",
    "createDate",
    "createUser",
    "dateIdentified",
    "identifiedBy",
    "isBaseline",
    "isTemplate",
    "lastUpdateDate",
    "lastUpdateUser",
    "lowerThreshold",
    "name",
    "notes",
    "obsName",
    "obsObjectId",
    "objectId",
    "priority",
    "projectId",
    "projectName",
    "projectObjectId",
    "projectThresholdObjectId",
    "rawTextNote",
    "resolutionDate",
    "resourceId",
    "resourceName",
    "resourceObjectId",
    "status",
    "thresholdParameterObjectId",
    "upperThreshold",
    "wbsCode",
    "wbsName",
    "wbsObjectId",
    "udf"
})
class ProjectIssueType {

    /**
     * Gets the value of the activityId property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the activityId property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ActivityId")
    var activityId: String
    /**
     * Gets the value of the activityName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the activityName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ActivityName")
    var activityName: String
    /**
     * Gets the value of the activityObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the activityObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ActivityObjectId", nillable = true)
    var activityObjectId: Integer
    /**
     * Gets the value of the actualValue property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the actualValue property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "ActualValue", nillable = true)
    var actualValue: Double
    /**
     * Gets the value of the createDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the createDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "CreateDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var createDate: Date
    /**
     * Gets the value of the createUser property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the createUser property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "CreateUser")
    var createUser: String
    /**
     * Gets the value of the dateIdentified property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the dateIdentified property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "DateIdentified", type = String::class)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var dateIdentified: Date
    /**
     * Gets the value of the identifiedBy property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the identifiedBy property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "IdentifiedBy")
    var identifiedBy: String
    /**
     * Gets the value of the isBaseline property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the isBaseline property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "IsBaseline")
    var isIsBaseline: Boolean
    /**
     * Gets the value of the isTemplate property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the isTemplate property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "IsTemplate")
    var isIsTemplate: Boolean
    /**
     * Gets the value of the lastUpdateDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the lastUpdateDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "LastUpdateDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var lastUpdateDate: Date
    /**
     * Gets the value of the lastUpdateUser property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the lastUpdateUser property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "LastUpdateUser")
    var lastUpdateUser: String
    /**
     * Gets the value of the lowerThreshold property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the lowerThreshold property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "LowerThreshold", nillable = true)
    var lowerThreshold: Double
    /**
     * Gets the value of the name property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the name property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Name")
    var name: String
    /**
     * Gets the value of the notes property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the notes property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Notes")
    var notes: String
    /**
     * Gets the value of the obsName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the obsName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "OBSName")
    var obsName: String
    /**
     * Gets the value of the obsObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the obsObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "OBSObjectId")
    var obsObjectId: Integer
    /**
     * Gets the value of the objectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the objectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ObjectId")
    var objectId: Integer
    /**
     * Gets the value of the priority property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the priority property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Priority")
    var priority: String
    /**
     * Gets the value of the projectId property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the projectId property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ProjectId")
    var projectId: String
    /**
     * Gets the value of the projectName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the projectName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ProjectName")
    var projectName: String
    /**
     * Gets the value of the projectObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the projectObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ProjectObjectId")
    var projectObjectId: Integer
    /**
     * Gets the value of the projectThresholdObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the projectThresholdObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ProjectThresholdObjectId", nillable = true)
    var projectThresholdObjectId: Integer
    /**
     * Gets the value of the rawTextNote property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the rawTextNote property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "RawTextNote")
    var rawTextNote: String
    /**
     * Gets the value of the resolutionDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the resolutionDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ResolutionDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var resolutionDate: Date
    /**
     * Gets the value of the resourceId property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the resourceId property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ResourceId")
    var resourceId: String
    /**
     * Gets the value of the resourceName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the resourceName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ResourceName")
    var resourceName: String
    /**
     * Gets the value of the resourceObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the resourceObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ResourceObjectId", nillable = true)
    var resourceObjectId: Integer
    /**
     * Gets the value of the status property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the status property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Status")
    var status: String
    /**
     * Gets the value of the thresholdParameterObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the thresholdParameterObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ThresholdParameterObjectId", nillable = true)
    var thresholdParameterObjectId: Integer
    /**
     * Gets the value of the upperThreshold property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the upperThreshold property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "UpperThreshold", nillable = true)
    var upperThreshold: Double
    /**
     * Gets the value of the wbsCode property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the wbsCode property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "WBSCode")
    var wbsCode: String
    /**
     * Gets the value of the wbsName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the wbsName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "WBSName")
    var wbsName: String
    /**
     * Gets the value of the wbsObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the wbsObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "WBSObjectId", nillable = true)
    var wbsObjectId: Integer
    @XmlElement(name = "UDF")
    protected var udf: List<UDFAssignmentType>? = null

    /**
     * Gets the value of the udf property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the udf property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getUDF().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [UDFAssignmentType]
     *
     *
     */
    fun getUDF(): List<UDFAssignmentType> {
        if (udf == null) {
            udf = ArrayList<UDFAssignmentType>()
        }
        return this.udf
    }

}
