//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.09.18 at 02:35:45 PM BST
//

package net.sf.mpxj.primavera.schema

import java.util.Date
import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlSchemaType
import javax.xml.bind.annotation.XmlType
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter

/**
 *
 * Java class for RelationshipType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RelationshipType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="Aref" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="Arls" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="CreateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="CreateUser" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="IsPredecessorBaseline" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="IsPredecessorTemplate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="IsSuccessorBaseline" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="IsSuccessorTemplate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="Lag" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="-9.9999999999E10"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="LastUpdateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="LastUpdateUser" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="PredecessorActivityId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="PredecessorActivityName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="PredecessorActivityObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="PredecessorActivityType" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Task Dependent"/>
 * &lt;enumeration value="Resource Dependent"/>
 * &lt;enumeration value="Level of Effort"/>
 * &lt;enumeration value="Start Milestone"/>
 * &lt;enumeration value="Finish Milestone"/>
 * &lt;enumeration value="WBS Summary"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="PredecessorFinishDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="PredecessorProjectId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="PredecessorProjectObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="PredecessorStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="PredecessorWbsName" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="SuccessorActivityId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="SuccessorActivityName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="SuccessorActivityObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="SuccessorActivityType" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Task Dependent"/>
 * &lt;enumeration value="Resource Dependent"/>
 * &lt;enumeration value="Level of Effort"/>
 * &lt;enumeration value="Start Milestone"/>
 * &lt;enumeration value="Finish Milestone"/>
 * &lt;enumeration value="WBS Summary"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="SuccessorFinishDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="SuccessorProjectId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="SuccessorProjectObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="SuccessorStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="SuccessorWbsName" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="Type" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Finish to Start"/>
 * &lt;enumeration value="Finish to Finish"/>
 * &lt;enumeration value="Start to Start"/>
 * &lt;enumeration value="Start to Finish"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelationshipType", propOrder = {
    "aref",
    "arls",
    "createDate",
    "createUser",
    "isPredecessorBaseline",
    "isPredecessorTemplate",
    "isSuccessorBaseline",
    "isSuccessorTemplate",
    "lag",
    "lastUpdateDate",
    "lastUpdateUser",
    "objectId",
    "predecessorActivityId",
    "predecessorActivityName",
    "predecessorActivityObjectId",
    "predecessorActivityType",
    "predecessorFinishDate",
    "predecessorProjectId",
    "predecessorProjectObjectId",
    "predecessorStartDate",
    "predecessorWbsName",
    "successorActivityId",
    "successorActivityName",
    "successorActivityObjectId",
    "successorActivityType",
    "successorFinishDate",
    "successorProjectId",
    "successorProjectObjectId",
    "successorStartDate",
    "successorWbsName",
    "type"
})
class RelationshipType {

    /**
     * Gets the value of the aref property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the aref property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Aref", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var aref: Date
    /**
     * Gets the value of the arls property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the arls property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Arls", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var arls: Date
    /**
     * Gets the value of the createDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the createDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "CreateDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var createDate: Date
    /**
     * Gets the value of the createUser property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the createUser property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "CreateUser")
    var createUser: String
    /**
     * Gets the value of the isPredecessorBaseline property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the isPredecessorBaseline property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "IsPredecessorBaseline")
    var isIsPredecessorBaseline: Boolean
    /**
     * Gets the value of the isPredecessorTemplate property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the isPredecessorTemplate property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "IsPredecessorTemplate")
    var isIsPredecessorTemplate: Boolean
    /**
     * Gets the value of the isSuccessorBaseline property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the isSuccessorBaseline property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "IsSuccessorBaseline")
    var isIsSuccessorBaseline: Boolean
    /**
     * Gets the value of the isSuccessorTemplate property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the isSuccessorTemplate property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "IsSuccessorTemplate")
    var isIsSuccessorTemplate: Boolean
    /**
     * Gets the value of the lag property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the lag property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "Lag", nillable = true)
    var lag: Double
    /**
     * Gets the value of the lastUpdateDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the lastUpdateDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "LastUpdateDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var lastUpdateDate: Date
    /**
     * Gets the value of the lastUpdateUser property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the lastUpdateUser property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "LastUpdateUser")
    var lastUpdateUser: String
    /**
     * Gets the value of the objectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the objectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ObjectId")
    var objectId: Integer
    /**
     * Gets the value of the predecessorActivityId property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the predecessorActivityId property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PredecessorActivityId")
    var predecessorActivityId: String
    /**
     * Gets the value of the predecessorActivityName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the predecessorActivityName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PredecessorActivityName")
    var predecessorActivityName: String
    /**
     * Gets the value of the predecessorActivityObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the predecessorActivityObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "PredecessorActivityObjectId")
    var predecessorActivityObjectId: Integer
    /**
     * Gets the value of the predecessorActivityType property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the predecessorActivityType property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PredecessorActivityType")
    var predecessorActivityType: String
    /**
     * Gets the value of the predecessorFinishDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the predecessorFinishDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PredecessorFinishDate", type = String::class)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var predecessorFinishDate: Date
    /**
     * Gets the value of the predecessorProjectId property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the predecessorProjectId property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PredecessorProjectId")
    var predecessorProjectId: String
    /**
     * Gets the value of the predecessorProjectObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the predecessorProjectObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "PredecessorProjectObjectId", nillable = true)
    var predecessorProjectObjectId: Integer
    /**
     * Gets the value of the predecessorStartDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the predecessorStartDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PredecessorStartDate", type = String::class)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var predecessorStartDate: Date
    /**
     * Gets the value of the predecessorWbsName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the predecessorWbsName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PredecessorWbsName")
    var predecessorWbsName: String
    /**
     * Gets the value of the successorActivityId property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the successorActivityId property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "SuccessorActivityId")
    var successorActivityId: String
    /**
     * Gets the value of the successorActivityName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the successorActivityName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "SuccessorActivityName")
    var successorActivityName: String
    /**
     * Gets the value of the successorActivityObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the successorActivityObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "SuccessorActivityObjectId")
    var successorActivityObjectId: Integer
    /**
     * Gets the value of the successorActivityType property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the successorActivityType property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "SuccessorActivityType")
    var successorActivityType: String
    /**
     * Gets the value of the successorFinishDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the successorFinishDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "SuccessorFinishDate", type = String::class)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var successorFinishDate: Date
    /**
     * Gets the value of the successorProjectId property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the successorProjectId property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "SuccessorProjectId")
    var successorProjectId: String
    /**
     * Gets the value of the successorProjectObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the successorProjectObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "SuccessorProjectObjectId", nillable = true)
    var successorProjectObjectId: Integer
    /**
     * Gets the value of the successorStartDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the successorStartDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "SuccessorStartDate", type = String::class)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var successorStartDate: Date
    /**
     * Gets the value of the successorWbsName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the successorWbsName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "SuccessorWbsName")
    var successorWbsName: String
    /**
     * Gets the value of the type property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the type property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Type")
    var type: String

}
