//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.09.18 at 02:35:45 PM BST
//

package net.sf.mpxj.primavera.schema

import java.util.Date
import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlSchemaType
import javax.xml.bind.annotation.XmlType
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter

/**
 *
 * Java class for ResourceAssignmentUpdateType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ResourceAssignmentUpdateType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="ActivityObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="ApprovalDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="ApprovalUserName" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ApprovalUserObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="ChangeSetObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="HeldDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="OverrideActualFinishDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="OverrideActualStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="OverrideActualUnits" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="0.0"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="OverrideRemainingDuration" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="0.0"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="OverrideRemainingFinishDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="OverrideRemainingUnits" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="0.0"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="PendingActualFinishDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="PendingActualStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="PendingActualUnits" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="0.0"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="PendingRemainingDuration" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="0.0"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="PendingRemainingFinishDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="PendingRemainingUnits" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="0.0"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ProjectObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="RequestUserObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="ResourceAssignmentObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Status" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Pending"/>
 * &lt;enumeration value="Held"/>
 * &lt;enumeration value="Approved"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceAssignmentUpdateType", propOrder = {
    "activityObjectId",
    "approvalDate",
    "approvalUserName",
    "approvalUserObjectId",
    "changeSetObjectId",
    "date",
    "heldDate",
    "overrideActualFinishDate",
    "overrideActualStartDate",
    "overrideActualUnits",
    "overrideRemainingDuration",
    "overrideRemainingFinishDate",
    "overrideRemainingUnits",
    "pendingActualFinishDate",
    "pendingActualStartDate",
    "pendingActualUnits",
    "pendingRemainingDuration",
    "pendingRemainingFinishDate",
    "pendingRemainingUnits",
    "projectObjectId",
    "requestUserObjectId",
    "resourceAssignmentObjectId",
    "status"
})
class ResourceAssignmentUpdateType {

    /**
     * Gets the value of the activityObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the activityObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ActivityObjectId")
    var activityObjectId: Integer
    /**
     * Gets the value of the approvalDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the approvalDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ApprovalDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var approvalDate: Date
    /**
     * Gets the value of the approvalUserName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the approvalUserName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ApprovalUserName")
    var approvalUserName: String
    /**
     * Gets the value of the approvalUserObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the approvalUserObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ApprovalUserObjectId", nillable = true)
    var approvalUserObjectId: Integer
    /**
     * Gets the value of the changeSetObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the changeSetObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ChangeSetObjectId")
    var changeSetObjectId: Integer
    /**
     * Gets the value of the date property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the date property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Date", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var date: Date
    /**
     * Gets the value of the heldDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the heldDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "HeldDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var heldDate: Date
    /**
     * Gets the value of the overrideActualFinishDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the overrideActualFinishDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "OverrideActualFinishDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var overrideActualFinishDate: Date
    /**
     * Gets the value of the overrideActualStartDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the overrideActualStartDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "OverrideActualStartDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var overrideActualStartDate: Date
    /**
     * Gets the value of the overrideActualUnits property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the overrideActualUnits property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "OverrideActualUnits", nillable = true)
    var overrideActualUnits: Double
    /**
     * Gets the value of the overrideRemainingDuration property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the overrideRemainingDuration property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "OverrideRemainingDuration", nillable = true)
    var overrideRemainingDuration: Double
    /**
     * Gets the value of the overrideRemainingFinishDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the overrideRemainingFinishDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "OverrideRemainingFinishDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var overrideRemainingFinishDate: Date
    /**
     * Gets the value of the overrideRemainingUnits property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the overrideRemainingUnits property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "OverrideRemainingUnits", nillable = true)
    var overrideRemainingUnits: Double
    /**
     * Gets the value of the pendingActualFinishDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the pendingActualFinishDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PendingActualFinishDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var pendingActualFinishDate: Date
    /**
     * Gets the value of the pendingActualStartDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the pendingActualStartDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PendingActualStartDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var pendingActualStartDate: Date
    /**
     * Gets the value of the pendingActualUnits property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the pendingActualUnits property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "PendingActualUnits", nillable = true)
    var pendingActualUnits: Double
    /**
     * Gets the value of the pendingRemainingDuration property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the pendingRemainingDuration property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "PendingRemainingDuration", nillable = true)
    var pendingRemainingDuration: Double
    /**
     * Gets the value of the pendingRemainingFinishDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the pendingRemainingFinishDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PendingRemainingFinishDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var pendingRemainingFinishDate: Date
    /**
     * Gets the value of the pendingRemainingUnits property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the pendingRemainingUnits property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "PendingRemainingUnits", nillable = true)
    var pendingRemainingUnits: Double
    /**
     * Gets the value of the projectObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the projectObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ProjectObjectId")
    var projectObjectId: Integer
    /**
     * Gets the value of the requestUserObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the requestUserObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "RequestUserObjectId", nillable = true)
    var requestUserObjectId: Integer
    /**
     * Gets the value of the resourceAssignmentObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the resourceAssignmentObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ResourceAssignmentObjectId")
    var resourceAssignmentObjectId: Integer
    /**
     * Gets the value of the status property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the status property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Status")
    var status: String

}
