//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.09.18 at 02:35:45 PM BST
//

package net.sf.mpxj.primavera.schema

import java.util.Date
import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlSchemaType
import javax.xml.bind.annotation.XmlType
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter

/**
 *
 * Java class for RiskMatrixScoreType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RiskMatrixScoreType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="CreateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="CreateUser" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="LastUpdateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="LastUpdateUser" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="ProbabilityThresholdLevel" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 * &lt;minInclusive value="1"/>
 * &lt;maxInclusive value="9"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="RiskMatrixName" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="40"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="RiskMatrixObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Severity1" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Severity1Label" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="40"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="Severity2" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Severity2Label" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="40"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="Severity3" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Severity3Label" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="40"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="Severity4" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Severity4Label" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="40"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="Severity5" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Severity5Label" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="40"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="Severity6" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Severity6Label" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="40"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="Severity7" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Severity7Label" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="40"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="Severity8" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Severity8Label" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="40"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="Severity9" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Severity9Label" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="40"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RiskMatrixScoreType", propOrder = {
    "createDate",
    "createUser",
    "lastUpdateDate",
    "lastUpdateUser",
    "objectId",
    "probabilityThresholdLevel",
    "riskMatrixName",
    "riskMatrixObjectId",
    "severity1",
    "severity1Label",
    "severity2",
    "severity2Label",
    "severity3",
    "severity3Label",
    "severity4",
    "severity4Label",
    "severity5",
    "severity5Label",
    "severity6",
    "severity6Label",
    "severity7",
    "severity7Label",
    "severity8",
    "severity8Label",
    "severity9",
    "severity9Label"
})
class RiskMatrixScoreType {

    /**
     * Gets the value of the createDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the createDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "CreateDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var createDate: Date
    /**
     * Gets the value of the createUser property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the createUser property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "CreateUser")
    var createUser: String
    /**
     * Gets the value of the lastUpdateDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the lastUpdateDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "LastUpdateDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var lastUpdateDate: Date
    /**
     * Gets the value of the lastUpdateUser property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the lastUpdateUser property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "LastUpdateUser")
    var lastUpdateUser: String
    /**
     * Gets the value of the objectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the objectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ObjectId")
    var objectId: Integer
    /**
     * Gets the value of the probabilityThresholdLevel property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the probabilityThresholdLevel property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ProbabilityThresholdLevel")
    var probabilityThresholdLevel: Integer
    /**
     * Gets the value of the riskMatrixName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the riskMatrixName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "RiskMatrixName")
    var riskMatrixName: String
    /**
     * Gets the value of the riskMatrixObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the riskMatrixObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "RiskMatrixObjectId")
    var riskMatrixObjectId: Integer
    /**
     * Gets the value of the severity1 property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the severity1 property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "Severity1", nillable = true)
    var severity1: Integer
    /**
     * Gets the value of the severity1Label property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the severity1Label property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Severity1Label")
    var severity1Label: String
    /**
     * Gets the value of the severity2 property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the severity2 property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "Severity2", nillable = true)
    var severity2: Integer
    /**
     * Gets the value of the severity2Label property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the severity2Label property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Severity2Label")
    var severity2Label: String
    /**
     * Gets the value of the severity3 property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the severity3 property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "Severity3", nillable = true)
    var severity3: Integer
    /**
     * Gets the value of the severity3Label property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the severity3Label property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Severity3Label")
    var severity3Label: String
    /**
     * Gets the value of the severity4 property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the severity4 property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "Severity4", nillable = true)
    var severity4: Integer
    /**
     * Gets the value of the severity4Label property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the severity4Label property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Severity4Label")
    var severity4Label: String
    /**
     * Gets the value of the severity5 property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the severity5 property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "Severity5", nillable = true)
    var severity5: Integer
    /**
     * Gets the value of the severity5Label property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the severity5Label property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Severity5Label")
    var severity5Label: String
    /**
     * Gets the value of the severity6 property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the severity6 property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "Severity6", nillable = true)
    var severity6: Integer
    /**
     * Gets the value of the severity6Label property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the severity6Label property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Severity6Label")
    var severity6Label: String
    /**
     * Gets the value of the severity7 property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the severity7 property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "Severity7", nillable = true)
    var severity7: Integer
    /**
     * Gets the value of the severity7Label property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the severity7Label property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Severity7Label")
    var severity7Label: String
    /**
     * Gets the value of the severity8 property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the severity8 property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "Severity8", nillable = true)
    var severity8: Integer
    /**
     * Gets the value of the severity8Label property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the severity8Label property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Severity8Label")
    var severity8Label: String
    /**
     * Gets the value of the severity9 property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the severity9 property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "Severity9", nillable = true)
    var severity9: Integer
    /**
     * Gets the value of the severity9Label property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the severity9Label property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Severity9Label")
    var severity9Label: String

}
