//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.09.18 at 02:35:45 PM BST
//

package net.sf.mpxj.primavera.schema

import java.util.Date
import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlSchemaType
import javax.xml.bind.annotation.XmlType
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter

/**
 *
 * Java class for ScheduleOptionsType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ScheduleOptionsType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="CalculateFloatBasedOnFinishDate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="ComputeTotalFloatType" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Start Float = Late Start - Early Start"/>
 * &lt;enumeration value="Finish Float = Late Finish - Early Finish"/>
 * &lt;enumeration value="Smallest of Start Float and Finish Float"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="CreateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="CreateUser" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="CriticalActivityFloatThreshold" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 * &lt;element name="CriticalActivityPathType" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Critical Float"/>
 * &lt;enumeration value="Longest Path"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="IgnoreOtherProjectRelationships" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="LastUpdateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="LastUpdateUser" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="LevelResourcesDuringScheduling" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="MakeOpenEndedActivitiesCritical" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="MaximumMultipleFloatPaths" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 * &lt;minInclusive value="0"/>
 * &lt;maxInclusive value="1000"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="MultipleFloatPathsEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="MultipleFloatPathsEndingActivityObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="MultipleFloatPathsUseTotalFloat" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="OutOfSequenceScheduleType" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value=""/>
 * &lt;enumeration value="Retained Logic"/>
 * &lt;enumeration value="Progress Override"/>
 * &lt;enumeration value="Actual Dates"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ProjectId" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="40"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ProjectObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="RecalculateResourceCosts" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="RelationshipLagCalendar" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Predecessor Activity Calendar"/>
 * &lt;enumeration value="Successor Activity Calendar"/>
 * &lt;enumeration value="24 Hour Calendar"/>
 * &lt;enumeration value="Project Default Calendar"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="StartToStartLagCalculationType" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="UseExpectedFinishDates" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="UserName" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="UserObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScheduleOptionsType", propOrder = {
    "calculateFloatBasedOnFinishDate",
    "computeTotalFloatType",
    "createDate",
    "createUser",
    "criticalActivityFloatThreshold",
    "criticalActivityPathType",
    "ignoreOtherProjectRelationships",
    "lastUpdateDate",
    "lastUpdateUser",
    "levelResourcesDuringScheduling",
    "makeOpenEndedActivitiesCritical",
    "maximumMultipleFloatPaths",
    "multipleFloatPathsEnabled",
    "multipleFloatPathsEndingActivityObjectId",
    "multipleFloatPathsUseTotalFloat",
    "outOfSequenceScheduleType",
    "projectId",
    "projectObjectId",
    "recalculateResourceCosts",
    "relationshipLagCalendar",
    "startToStartLagCalculationType",
    "useExpectedFinishDates",
    "userName",
    "userObjectId"
})
class ScheduleOptionsType {

    /**
     * Gets the value of the calculateFloatBasedOnFinishDate property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the calculateFloatBasedOnFinishDate property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "CalculateFloatBasedOnFinishDate", nillable = true)
    var isCalculateFloatBasedOnFinishDate: Boolean
    /**
     * Gets the value of the computeTotalFloatType property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the computeTotalFloatType property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ComputeTotalFloatType")
    var computeTotalFloatType: String
    /**
     * Gets the value of the createDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the createDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "CreateDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var createDate: Date
    /**
     * Gets the value of the createUser property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the createUser property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "CreateUser")
    var createUser: String
    /**
     * Gets the value of the criticalActivityFloatThreshold property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the criticalActivityFloatThreshold property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "CriticalActivityFloatThreshold", nillable = true)
    var criticalActivityFloatThreshold: Double
    /**
     * Gets the value of the criticalActivityPathType property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the criticalActivityPathType property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "CriticalActivityPathType")
    var criticalActivityPathType: String
    /**
     * Gets the value of the ignoreOtherProjectRelationships property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the ignoreOtherProjectRelationships property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "IgnoreOtherProjectRelationships", nillable = true)
    var isIgnoreOtherProjectRelationships: Boolean
    /**
     * Gets the value of the lastUpdateDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the lastUpdateDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "LastUpdateDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var lastUpdateDate: Date
    /**
     * Gets the value of the lastUpdateUser property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the lastUpdateUser property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "LastUpdateUser")
    var lastUpdateUser: String
    /**
     * Gets the value of the levelResourcesDuringScheduling property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the levelResourcesDuringScheduling property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "LevelResourcesDuringScheduling", nillable = true)
    var isLevelResourcesDuringScheduling: Boolean
    /**
     * Gets the value of the makeOpenEndedActivitiesCritical property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the makeOpenEndedActivitiesCritical property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "MakeOpenEndedActivitiesCritical", nillable = true)
    var isMakeOpenEndedActivitiesCritical: Boolean
    /**
     * Gets the value of the maximumMultipleFloatPaths property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the maximumMultipleFloatPaths property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "MaximumMultipleFloatPaths", nillable = true)
    var maximumMultipleFloatPaths: Integer
    /**
     * Gets the value of the multipleFloatPathsEnabled property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the multipleFloatPathsEnabled property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "MultipleFloatPathsEnabled", nillable = true)
    var isMultipleFloatPathsEnabled: Boolean
    /**
     * Gets the value of the multipleFloatPathsEndingActivityObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the multipleFloatPathsEndingActivityObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "MultipleFloatPathsEndingActivityObjectId", nillable = true)
    var multipleFloatPathsEndingActivityObjectId: Integer
    /**
     * Gets the value of the multipleFloatPathsUseTotalFloat property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the multipleFloatPathsUseTotalFloat property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "MultipleFloatPathsUseTotalFloat", nillable = true)
    var isMultipleFloatPathsUseTotalFloat: Boolean
    /**
     * Gets the value of the outOfSequenceScheduleType property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the outOfSequenceScheduleType property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "OutOfSequenceScheduleType")
    var outOfSequenceScheduleType: String
    /**
     * Gets the value of the projectId property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the projectId property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ProjectId")
    var projectId: String
    /**
     * Gets the value of the projectObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the projectObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ProjectObjectId", nillable = true)
    var projectObjectId: Integer
    /**
     * Gets the value of the recalculateResourceCosts property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the recalculateResourceCosts property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "RecalculateResourceCosts", nillable = true)
    var isRecalculateResourceCosts: Boolean
    /**
     * Gets the value of the relationshipLagCalendar property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the relationshipLagCalendar property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "RelationshipLagCalendar")
    var relationshipLagCalendar: String
    /**
     * Gets the value of the startToStartLagCalculationType property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the startToStartLagCalculationType property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "StartToStartLagCalculationType", nillable = true)
    var isStartToStartLagCalculationType: Boolean
    /**
     * Gets the value of the useExpectedFinishDates property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the useExpectedFinishDates property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "UseExpectedFinishDates", nillable = true)
    var isUseExpectedFinishDates: Boolean
    /**
     * Gets the value of the userName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the userName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "UserName")
    var userName: String
    /**
     * Gets the value of the userObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the userObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "UserObjectId", nillable = true)
    var userObjectId: Integer

}
