//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.09.18 at 02:35:45 PM BST
//

package net.sf.mpxj.primavera.schema

import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlType

/**
 *
 * Java class for ScheduleCheckOptionType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ScheduleCheckOptionType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="BEITripwireTarget" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="0.0"/>
 * &lt;maxInclusive value="1.0"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="CheckBEITripwire" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="CheckHardConstraints" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="CheckInvalidProgress" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="CheckLags" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="CheckLargeDurations" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="CheckLargeFloat" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="CheckLateActivities" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="CheckLogic" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="CheckLongLags" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="CheckNegativeFloat" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="CheckNegativeLags" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="CheckRelationShips" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="CheckResources" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="CheckSoftConstraints" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="HardConstraintTarget" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 * &lt;minInclusive value="0"/>
 * &lt;maxInclusive value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="LagsTarget" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 * &lt;minInclusive value="0"/>
 * &lt;maxInclusive value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="LargeDurationCriteria" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 * &lt;minInclusive value="0"/>
 * &lt;maxInclusive value="2147483647"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="LargeDurationTarget" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 * &lt;minInclusive value="0"/>
 * &lt;maxInclusive value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="LargeFloatCriteria" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 * &lt;minInclusive value="0"/>
 * &lt;maxInclusive value="2147483647"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="LargeFloatTarget" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 * &lt;minInclusive value="0"/>
 * &lt;maxInclusive value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="LateActivitiesTarget" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 * &lt;minInclusive value="0"/>
 * &lt;maxInclusive value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="LogicTarget" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 * &lt;minInclusive value="0"/>
 * &lt;maxInclusive value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="LongLagsCriteria" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 * &lt;minInclusive value="0"/>
 * &lt;maxInclusive value="2147483647"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="LongLagsTarget" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 * &lt;minInclusive value="0"/>
 * &lt;maxInclusive value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="NegativeFloatTarget" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 * &lt;minInclusive value="0"/>
 * &lt;maxInclusive value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="NegativeLagsTarget" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 * &lt;minInclusive value="0"/>
 * &lt;maxInclusive value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ProgressDateTarget" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 * &lt;minInclusive value="0"/>
 * &lt;maxInclusive value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ProjPropTypeInt" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="ProjectObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="PropValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="RelationshipTarget" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 * &lt;minInclusive value="0"/>
 * &lt;maxInclusive value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ResourcesTarget" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 * &lt;minInclusive value="0"/>
 * &lt;maxInclusive value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ScheduleCheckData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="ScheduleCheckOptionsId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="SoftConstraintTarget" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 * &lt;minInclusive value="0"/>
 * &lt;maxInclusive value="100"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScheduleCheckOptionType", propOrder = {
    "beiTripwireTarget",
    "checkBEITripwire",
    "checkHardConstraints",
    "checkInvalidProgress",
    "checkLags",
    "checkLargeDurations",
    "checkLargeFloat",
    "checkLateActivities",
    "checkLogic",
    "checkLongLags",
    "checkNegativeFloat",
    "checkNegativeLags",
    "checkRelationShips",
    "checkResources",
    "checkSoftConstraints",
    "hardConstraintTarget",
    "lagsTarget",
    "largeDurationCriteria",
    "largeDurationTarget",
    "largeFloatCriteria",
    "largeFloatTarget",
    "lateActivitiesTarget",
    "logicTarget",
    "longLagsCriteria",
    "longLagsTarget",
    "negativeFloatTarget",
    "negativeLagsTarget",
    "progressDateTarget",
    "projPropTypeInt",
    "projectObjectId",
    "propValue",
    "relationshipTarget",
    "resourcesTarget",
    "scheduleCheckData",
    "scheduleCheckOptionsId",
    "softConstraintTarget"
})
class ScheduleCheckOptionType {

    /**
     * Gets the value of the beiTripwireTarget property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the beiTripwireTarget property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "BEITripwireTarget", nillable = true)
    var beiTripwireTarget: Double
    /**
     * Gets the value of the checkBEITripwire property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the checkBEITripwire property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "CheckBEITripwire", nillable = true)
    var isCheckBEITripwire: Boolean
    /**
     * Gets the value of the checkHardConstraints property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the checkHardConstraints property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "CheckHardConstraints", nillable = true)
    var isCheckHardConstraints: Boolean
    /**
     * Gets the value of the checkInvalidProgress property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the checkInvalidProgress property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "CheckInvalidProgress", nillable = true)
    var isCheckInvalidProgress: Boolean
    /**
     * Gets the value of the checkLags property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the checkLags property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "CheckLags", nillable = true)
    var isCheckLags: Boolean
    /**
     * Gets the value of the checkLargeDurations property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the checkLargeDurations property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "CheckLargeDurations", nillable = true)
    var isCheckLargeDurations: Boolean
    /**
     * Gets the value of the checkLargeFloat property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the checkLargeFloat property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "CheckLargeFloat", nillable = true)
    var isCheckLargeFloat: Boolean
    /**
     * Gets the value of the checkLateActivities property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the checkLateActivities property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "CheckLateActivities", nillable = true)
    var isCheckLateActivities: Boolean
    /**
     * Gets the value of the checkLogic property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the checkLogic property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "CheckLogic", nillable = true)
    var isCheckLogic: Boolean
    /**
     * Gets the value of the checkLongLags property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the checkLongLags property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "CheckLongLags", nillable = true)
    var isCheckLongLags: Boolean
    /**
     * Gets the value of the checkNegativeFloat property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the checkNegativeFloat property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "CheckNegativeFloat", nillable = true)
    var isCheckNegativeFloat: Boolean
    /**
     * Gets the value of the checkNegativeLags property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the checkNegativeLags property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "CheckNegativeLags", nillable = true)
    var isCheckNegativeLags: Boolean
    /**
     * Gets the value of the checkRelationShips property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the checkRelationShips property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "CheckRelationShips", nillable = true)
    var isCheckRelationShips: Boolean
    /**
     * Gets the value of the checkResources property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the checkResources property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "CheckResources", nillable = true)
    var isCheckResources: Boolean
    /**
     * Gets the value of the checkSoftConstraints property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the checkSoftConstraints property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "CheckSoftConstraints", nillable = true)
    var isCheckSoftConstraints: Boolean
    /**
     * Gets the value of the hardConstraintTarget property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the hardConstraintTarget property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "HardConstraintTarget", nillable = true)
    var hardConstraintTarget: Integer
    /**
     * Gets the value of the lagsTarget property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the lagsTarget property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "LagsTarget", nillable = true)
    var lagsTarget: Integer
    /**
     * Gets the value of the largeDurationCriteria property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the largeDurationCriteria property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "LargeDurationCriteria", nillable = true)
    var largeDurationCriteria: Integer
    /**
     * Gets the value of the largeDurationTarget property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the largeDurationTarget property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "LargeDurationTarget", nillable = true)
    var largeDurationTarget: Integer
    /**
     * Gets the value of the largeFloatCriteria property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the largeFloatCriteria property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "LargeFloatCriteria", nillable = true)
    var largeFloatCriteria: Integer
    /**
     * Gets the value of the largeFloatTarget property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the largeFloatTarget property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "LargeFloatTarget", nillable = true)
    var largeFloatTarget: Integer
    /**
     * Gets the value of the lateActivitiesTarget property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the lateActivitiesTarget property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "LateActivitiesTarget", nillable = true)
    var lateActivitiesTarget: Integer
    /**
     * Gets the value of the logicTarget property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the logicTarget property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "LogicTarget", nillable = true)
    var logicTarget: Integer
    /**
     * Gets the value of the longLagsCriteria property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the longLagsCriteria property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "LongLagsCriteria", nillable = true)
    var longLagsCriteria: Integer
    /**
     * Gets the value of the longLagsTarget property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the longLagsTarget property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "LongLagsTarget", nillable = true)
    var longLagsTarget: Integer
    /**
     * Gets the value of the negativeFloatTarget property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the negativeFloatTarget property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "NegativeFloatTarget", nillable = true)
    var negativeFloatTarget: Integer
    /**
     * Gets the value of the negativeLagsTarget property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the negativeLagsTarget property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "NegativeLagsTarget", nillable = true)
    var negativeLagsTarget: Integer
    /**
     * Gets the value of the progressDateTarget property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the progressDateTarget property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ProgressDateTarget", nillable = true)
    var progressDateTarget: Integer
    /**
     * Gets the value of the projPropTypeInt property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the projPropTypeInt property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ProjPropTypeInt", nillable = true)
    var projPropTypeInt: Integer
    /**
     * Gets the value of the projectObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the projectObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ProjectObjectId")
    var projectObjectId: Integer
    /**
     * Gets the value of the propValue property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the propValue property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PropValue")
    var propValue: String
    /**
     * Gets the value of the relationshipTarget property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the relationshipTarget property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "RelationshipTarget", nillable = true)
    var relationshipTarget: Integer
    /**
     * Gets the value of the resourcesTarget property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the resourcesTarget property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ResourcesTarget", nillable = true)
    var resourcesTarget: Integer
    /**
     * Gets the value of the scheduleCheckData property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the scheduleCheckData property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ScheduleCheckData")
    var scheduleCheckData: String
    /**
     * Gets the value of the scheduleCheckOptionsId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the scheduleCheckOptionsId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ScheduleCheckOptionsId")
    var scheduleCheckOptionsId: Integer
    /**
     * Gets the value of the softConstraintTarget property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the softConstraintTarget property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "SoftConstraintTarget", nillable = true)
    var softConstraintTarget: Integer

}
