//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.09.18 at 02:35:45 PM BST
//

package net.sf.mpxj.primavera.schema

import java.util.Date
import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlSchemaType
import javax.xml.bind.annotation.XmlType
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter

/**
 *
 * Java class for UDFValueType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="UDFValueType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="CodeValue" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="60"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ConditionalIndicator" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Cost" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 * &lt;element name="CreateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="CreateUser" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="Description" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="Double" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="-1.0E12"/>
 * &lt;maxInclusive value="1.0E12"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="FinishDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="ForeignObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Indicator" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value=""/>
 * &lt;enumeration value="None"/>
 * &lt;enumeration value="Red"/>
 * &lt;enumeration value="Yellow"/>
 * &lt;enumeration value="Green"/>
 * &lt;enumeration value="Blue"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="Integer" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="IsBaseline" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="IsTemplate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="IsUDFTypeCalculated" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="IsUDFTypeConditional" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="LastUpdateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="LastUpdateUser" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ProjectObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="Text" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="UDFCodeObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="UDFTypeDataType" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Text"/>
 * &lt;enumeration value="Start Date"/>
 * &lt;enumeration value="Finish Date"/>
 * &lt;enumeration value="Cost"/>
 * &lt;enumeration value="Double"/>
 * &lt;enumeration value="Integer"/>
 * &lt;enumeration value="Indicator"/>
 * &lt;enumeration value="Code"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="UDFTypeObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="UDFTypeSubjectArea" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Activity"/>
 * &lt;enumeration value="Activity Expense"/>
 * &lt;enumeration value="Activity Step"/>
 * &lt;enumeration value="Project"/>
 * &lt;enumeration value="Project Issue"/>
 * &lt;enumeration value="Project Risk"/>
 * &lt;enumeration value="Resource"/>
 * &lt;enumeration value="Resource Assignment"/>
 * &lt;enumeration value="WBS"/>
 * &lt;enumeration value="Work Products and Documents"/>
 * &lt;enumeration value="Activity Step Template Item"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="UDFTypeTitle" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="40"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UDFValueType", propOrder = {
    "codeValue",
    "conditionalIndicator",
    "cost",
    "createDate",
    "createUser",
    "description",
    "_double",
    "finishDate",
    "foreignObjectId",
    "indicator",
    "integer",
    "isBaseline",
    "isTemplate",
    "isUDFTypeCalculated",
    "isUDFTypeConditional",
    "lastUpdateDate",
    "lastUpdateUser",
    "projectObjectId",
    "startDate",
    "text",
    "udfCodeObjectId",
    "udfTypeDataType",
    "udfTypeObjectId",
    "udfTypeSubjectArea",
    "udfTypeTitle"
})
class UDFValueType {

    /**
     * Gets the value of the codeValue property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the codeValue property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "CodeValue")
    var codeValue: String
    /**
     * Gets the value of the conditionalIndicator property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the conditionalIndicator property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ConditionalIndicator", nillable = true)
    var conditionalIndicator: Integer
    /**
     * Gets the value of the cost property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the cost property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "Cost", nillable = true)
    var cost: Double
    /**
     * Gets the value of the createDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the createDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "CreateDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var createDate: Date
    /**
     * Gets the value of the createUser property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the createUser property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "CreateUser")
    var createUser: String
    /**
     * Gets the value of the description property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the description property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Description")
    var description: String
    /**
     * Gets the value of the double property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the double property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "Double", nillable = true)
    var double: Double
    /**
     * Gets the value of the finishDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the finishDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "FinishDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var finishDate: Date
    /**
     * Gets the value of the foreignObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the foreignObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ForeignObjectId")
    var foreignObjectId: Integer
    /**
     * Gets the value of the indicator property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the indicator property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Indicator")
    var indicator: String
    /**
     * Gets the value of the integer property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the integer property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "Integer", nillable = true)
    var integer: Integer
    /**
     * Gets the value of the isBaseline property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the isBaseline property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "IsBaseline", nillable = true)
    var isIsBaseline: Boolean
    /**
     * Gets the value of the isTemplate property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the isTemplate property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "IsTemplate")
    var isIsTemplate: Boolean
    /**
     * Gets the value of the isUDFTypeCalculated property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the isUDFTypeCalculated property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "IsUDFTypeCalculated", nillable = true)
    var isIsUDFTypeCalculated: Boolean
    /**
     * Gets the value of the isUDFTypeConditional property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the isUDFTypeConditional property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "IsUDFTypeConditional", nillable = true)
    var isIsUDFTypeConditional: Boolean
    /**
     * Gets the value of the lastUpdateDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the lastUpdateDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "LastUpdateDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var lastUpdateDate: Date
    /**
     * Gets the value of the lastUpdateUser property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the lastUpdateUser property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "LastUpdateUser")
    var lastUpdateUser: String
    /**
     * Gets the value of the projectObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the projectObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ProjectObjectId", nillable = true)
    var projectObjectId: Integer
    /**
     * Gets the value of the startDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the startDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "StartDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var startDate: Date
    /**
     * Gets the value of the text property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the text property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Text")
    var text: String
    /**
     * Gets the value of the udfCodeObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the udfCodeObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "UDFCodeObjectId", nillable = true)
    var udfCodeObjectId: Integer
    /**
     * Gets the value of the udfTypeDataType property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the udfTypeDataType property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "UDFTypeDataType")
    var udfTypeDataType: String
    /**
     * Gets the value of the udfTypeObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the udfTypeObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "UDFTypeObjectId")
    var udfTypeObjectId: Integer
    /**
     * Gets the value of the udfTypeSubjectArea property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the udfTypeSubjectArea property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "UDFTypeSubjectArea")
    var udfTypeSubjectArea: String
    /**
     * Gets the value of the udfTypeTitle property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the udfTypeTitle property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "UDFTypeTitle")
    var udfTypeTitle: String

}
