//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.09.18 at 02:35:45 PM BST
//

package net.sf.mpxj.primavera.schema

import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlType

/**
 *
 * Java class for UpdateBaselineOptionType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="UpdateBaselineOptionType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="ActivitiesFilter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="ActivitiesFilterLogic" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ActivityCodeAssignments" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="ActivityFilterId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="ActivityFilterName" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ActivityInformation" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="ActivityNotebooks" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="ActivityRsrcAssignmentUdfs" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="ActivityUdfs" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="ActualUnitsCostWoRsrcAssignmnt" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="AddNewActivitiesData" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="AddNewRsrcRole" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="AllActivities" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="BatchModeEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="BudgetUnitsCost" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="BudgetUnitsCostWoRsrcAssignmnt" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="Constraints" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="DatesDurationDatadates" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="DeleteNonExistingActivities" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="ExpenseUdfs" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="Expenses" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="FilteredActivities" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="GeneralActivitiInfo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="IgnoreLastUpdateDate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="IssueUDFs" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="ObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="ProjectDetails" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="ProjectRisksIssuesAndThresholds" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="ProjectUDFs" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="Relationships" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="RiskAssignments" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="RiskUDFs" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="Steps" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="StepsUdf" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="UpdateExistRsrcRoleAssignment" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="UpdateExistingActivities" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="UserName" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="WPDocumentUDFs" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="WbsAssignments" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="WbsUDFs" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;element name="WorkProductsAndDocuments" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateBaselineOptionType", propOrder = {
    "activitiesFilter",
    "activitiesFilterLogic",
    "activityCodeAssignments",
    "activityFilterId",
    "activityFilterName",
    "activityInformation",
    "activityNotebooks",
    "activityRsrcAssignmentUdfs",
    "activityUdfs",
    "actualUnitsCostWoRsrcAssignmnt",
    "addNewActivitiesData",
    "addNewRsrcRole",
    "allActivities",
    "batchModeEnabled",
    "budgetUnitsCost",
    "budgetUnitsCostWoRsrcAssignmnt",
    "constraints",
    "datesDurationDatadates",
    "deleteNonExistingActivities",
    "expenseUdfs",
    "expenses",
    "filteredActivities",
    "generalActivitiInfo",
    "ignoreLastUpdateDate",
    "issueUDFs",
    "objectId",
    "projectDetails",
    "projectRisksIssuesAndThresholds",
    "projectUDFs",
    "relationships",
    "riskAssignments",
    "riskUDFs",
    "steps",
    "stepsUdf",
    "updateExistRsrcRoleAssignment",
    "updateExistingActivities",
    "userName",
    "wpDocumentUDFs",
    "wbsAssignments",
    "wbsUDFs",
    "workProductsAndDocuments"
})
class UpdateBaselineOptionType {

    /**
     * Gets the value of the activitiesFilter property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the activitiesFilter property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ActivitiesFilter")
    var activitiesFilter: String
    /**
     * Gets the value of the activitiesFilterLogic property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the activitiesFilterLogic property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ActivitiesFilterLogic")
    var activitiesFilterLogic: String
    /**
     * Gets the value of the activityCodeAssignments property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the activityCodeAssignments property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "ActivityCodeAssignments", nillable = true)
    var isActivityCodeAssignments: Boolean
    /**
     * Gets the value of the activityFilterId property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the activityFilterId property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ActivityFilterId")
    var activityFilterId: String
    /**
     * Gets the value of the activityFilterName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the activityFilterName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ActivityFilterName")
    var activityFilterName: String
    /**
     * Gets the value of the activityInformation property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the activityInformation property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "ActivityInformation", nillable = true)
    var isActivityInformation: Boolean
    /**
     * Gets the value of the activityNotebooks property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the activityNotebooks property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "ActivityNotebooks", nillable = true)
    var isActivityNotebooks: Boolean
    /**
     * Gets the value of the activityRsrcAssignmentUdfs property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the activityRsrcAssignmentUdfs property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "ActivityRsrcAssignmentUdfs", nillable = true)
    var isActivityRsrcAssignmentUdfs: Boolean
    /**
     * Gets the value of the activityUdfs property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the activityUdfs property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "ActivityUdfs", nillable = true)
    var isActivityUdfs: Boolean
    /**
     * Gets the value of the actualUnitsCostWoRsrcAssignmnt property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the actualUnitsCostWoRsrcAssignmnt property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "ActualUnitsCostWoRsrcAssignmnt", nillable = true)
    var isActualUnitsCostWoRsrcAssignmnt: Boolean
    /**
     * Gets the value of the addNewActivitiesData property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the addNewActivitiesData property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "AddNewActivitiesData", nillable = true)
    var isAddNewActivitiesData: Boolean
    /**
     * Gets the value of the addNewRsrcRole property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the addNewRsrcRole property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "AddNewRsrcRole", nillable = true)
    var isAddNewRsrcRole: Boolean
    /**
     * Gets the value of the allActivities property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the allActivities property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "AllActivities", nillable = true)
    var isAllActivities: Boolean
    /**
     * Gets the value of the batchModeEnabled property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the batchModeEnabled property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "BatchModeEnabled", nillable = true)
    var isBatchModeEnabled: Boolean
    /**
     * Gets the value of the budgetUnitsCost property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the budgetUnitsCost property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "BudgetUnitsCost", nillable = true)
    var isBudgetUnitsCost: Boolean
    /**
     * Gets the value of the budgetUnitsCostWoRsrcAssignmnt property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the budgetUnitsCostWoRsrcAssignmnt property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "BudgetUnitsCostWoRsrcAssignmnt", nillable = true)
    var isBudgetUnitsCostWoRsrcAssignmnt: Boolean
    /**
     * Gets the value of the constraints property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the constraints property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "Constraints", nillable = true)
    var isConstraints: Boolean
    /**
     * Gets the value of the datesDurationDatadates property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the datesDurationDatadates property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "DatesDurationDatadates", nillable = true)
    var isDatesDurationDatadates: Boolean
    /**
     * Gets the value of the deleteNonExistingActivities property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the deleteNonExistingActivities property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "DeleteNonExistingActivities", nillable = true)
    var isDeleteNonExistingActivities: Boolean
    /**
     * Gets the value of the expenseUdfs property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the expenseUdfs property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "ExpenseUdfs", nillable = true)
    var isExpenseUdfs: Boolean
    /**
     * Gets the value of the expenses property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the expenses property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "Expenses", nillable = true)
    var isExpenses: Boolean
    /**
     * Gets the value of the filteredActivities property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the filteredActivities property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "FilteredActivities", nillable = true)
    var isFilteredActivities: Boolean
    /**
     * Gets the value of the generalActivitiInfo property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the generalActivitiInfo property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "GeneralActivitiInfo", nillable = true)
    var isGeneralActivitiInfo: Boolean
    /**
     * Gets the value of the ignoreLastUpdateDate property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the ignoreLastUpdateDate property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "IgnoreLastUpdateDate", nillable = true)
    var isIgnoreLastUpdateDate: Boolean
    /**
     * Gets the value of the issueUDFs property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the issueUDFs property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "IssueUDFs", nillable = true)
    var isIssueUDFs: Boolean
    /**
     * Gets the value of the objectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the objectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ObjectId", nillable = true)
    var objectId: Integer
    /**
     * Gets the value of the projectDetails property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the projectDetails property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "ProjectDetails", nillable = true)
    var isProjectDetails: Boolean
    /**
     * Gets the value of the projectRisksIssuesAndThresholds property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the projectRisksIssuesAndThresholds property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "ProjectRisksIssuesAndThresholds", nillable = true)
    var isProjectRisksIssuesAndThresholds: Boolean
    /**
     * Gets the value of the projectUDFs property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the projectUDFs property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "ProjectUDFs", nillable = true)
    var isProjectUDFs: Boolean
    /**
     * Gets the value of the relationships property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the relationships property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "Relationships", nillable = true)
    var isRelationships: Boolean
    /**
     * Gets the value of the riskAssignments property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the riskAssignments property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "RiskAssignments", nillable = true)
    var isRiskAssignments: Boolean
    /**
     * Gets the value of the riskUDFs property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the riskUDFs property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "RiskUDFs", nillable = true)
    var isRiskUDFs: Boolean
    /**
     * Gets the value of the steps property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the steps property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "Steps", nillable = true)
    var isSteps: Boolean
    /**
     * Gets the value of the stepsUdf property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the stepsUdf property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "StepsUdf", nillable = true)
    var isStepsUdf: Boolean
    /**
     * Gets the value of the updateExistRsrcRoleAssignment property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the updateExistRsrcRoleAssignment property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "UpdateExistRsrcRoleAssignment", nillable = true)
    var isUpdateExistRsrcRoleAssignment: Boolean
    /**
     * Gets the value of the updateExistingActivities property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the updateExistingActivities property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "UpdateExistingActivities", nillable = true)
    var isUpdateExistingActivities: Boolean
    /**
     * Gets the value of the userName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the userName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "UserName")
    var userName: String
    /**
     * Gets the value of the wpDocumentUDFs property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the wpDocumentUDFs property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "WPDocumentUDFs", nillable = true)
    var isWPDocumentUDFs: Boolean
    /**
     * Gets the value of the wbsAssignments property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the wbsAssignments property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "WbsAssignments", nillable = true)
    var isWbsAssignments: Boolean
    /**
     * Gets the value of the wbsUDFs property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the wbsUDFs property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "WbsUDFs", nillable = true)
    var isWbsUDFs: Boolean
    /**
     * Gets the value of the workProductsAndDocuments property.
     *
     * @return
     * possible object is
     * [Boolean]
     */
    /**
     * Sets the value of the workProductsAndDocuments property.
     *
     * @param value
     * allowed object is
     * [Boolean]
     */
    @XmlElement(name = "WorkProductsAndDocuments", nillable = true)
    var isWorkProductsAndDocuments: Boolean

}
