//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.09.18 at 02:35:45 PM BST
//

package net.sf.mpxj.primavera.schema

import java.util.Date
import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlSchemaType
import javax.xml.bind.annotation.XmlType
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter

/**
 *
 * Java class for UserDefinedValueUpdateType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="UserDefinedValueUpdateType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="ApprovalDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="ApprovalUserName" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ApprovalUserObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="ChangeSetObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="ForeignObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="HeldDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="OverrideUDFRAGType" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value=""/>
 * &lt;enumeration value="None"/>
 * &lt;enumeration value="Red"/>
 * &lt;enumeration value="Yellow"/>
 * &lt;enumeration value="Green"/>
 * &lt;enumeration value="Blue"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="OverrideUdfCodeId" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="0.0"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="OverrideUdfCost" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 * &lt;element name="OverrideUdfEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="OverrideUdfInteger" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="OverrideUdfNumber" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="-1.0E12"/>
 * &lt;maxInclusive value="1.0E12"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="OverrideUdfStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="OverrideUdfText" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="PendingUDFRAGType" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value=""/>
 * &lt;enumeration value="None"/>
 * &lt;enumeration value="Red"/>
 * &lt;enumeration value="Yellow"/>
 * &lt;enumeration value="Green"/>
 * &lt;enumeration value="Blue"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="PendingUdfCodeId" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="0.0"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="PendingUdfCost" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 * &lt;element name="PendingUdfEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="PendingUdfInteger" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="PendingUdfNumber" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 * &lt;minInclusive value="-1.0E12"/>
 * &lt;maxInclusive value="1.0E12"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="PendingUdfStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 * &lt;element name="PendingUdfText" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;maxLength value="255"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="ProjectObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="RequestUserObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;element name="Status" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Pending"/>
 * &lt;enumeration value="Held"/>
 * &lt;enumeration value="Approved"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="UDFDataType" minOccurs="0">
 * &lt;simpleType>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 * &lt;enumeration value="Text"/>
 * &lt;enumeration value="Start Date"/>
 * &lt;enumeration value="Finish Date"/>
 * &lt;enumeration value="Cost"/>
 * &lt;enumeration value="Double"/>
 * &lt;enumeration value="Integer"/>
 * &lt;enumeration value="Indicator"/>
 * &lt;enumeration value="Code"/>
 * &lt;/restriction>
 * &lt;/simpleType>
 * &lt;/element>
 * &lt;element name="UDFTypeObjectId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserDefinedValueUpdateType", propOrder = {
    "approvalDate",
    "approvalUserName",
    "approvalUserObjectId",
    "changeSetObjectId",
    "date",
    "foreignObjectId",
    "heldDate",
    "overrideUDFRAGType",
    "overrideUdfCodeId",
    "overrideUdfCost",
    "overrideUdfEndDate",
    "overrideUdfInteger",
    "overrideUdfNumber",
    "overrideUdfStartDate",
    "overrideUdfText",
    "pendingUDFRAGType",
    "pendingUdfCodeId",
    "pendingUdfCost",
    "pendingUdfEndDate",
    "pendingUdfInteger",
    "pendingUdfNumber",
    "pendingUdfStartDate",
    "pendingUdfText",
    "projectObjectId",
    "requestUserObjectId",
    "status",
    "udfDataType",
    "udfTypeObjectId"
})
class UserDefinedValueUpdateType {

    /**
     * Gets the value of the approvalDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the approvalDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ApprovalDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var approvalDate: Date
    /**
     * Gets the value of the approvalUserName property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the approvalUserName property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "ApprovalUserName")
    var approvalUserName: String
    /**
     * Gets the value of the approvalUserObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the approvalUserObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ApprovalUserObjectId", nillable = true)
    var approvalUserObjectId: Integer
    /**
     * Gets the value of the changeSetObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the changeSetObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ChangeSetObjectId")
    var changeSetObjectId: Integer
    /**
     * Gets the value of the date property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the date property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Date", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var date: Date
    /**
     * Gets the value of the foreignObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the foreignObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ForeignObjectId")
    var foreignObjectId: Integer
    /**
     * Gets the value of the heldDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the heldDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "HeldDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var heldDate: Date
    /**
     * Gets the value of the overrideUDFRAGType property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the overrideUDFRAGType property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "OverrideUDFRAGType")
    var overrideUDFRAGType: String
    /**
     * Gets the value of the overrideUdfCodeId property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the overrideUdfCodeId property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "OverrideUdfCodeId", nillable = true)
    var overrideUdfCodeId: Double
    /**
     * Gets the value of the overrideUdfCost property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the overrideUdfCost property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "OverrideUdfCost", nillable = true)
    var overrideUdfCost: Double
    /**
     * Gets the value of the overrideUdfEndDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the overrideUdfEndDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "OverrideUdfEndDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var overrideUdfEndDate: Date
    /**
     * Gets the value of the overrideUdfInteger property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the overrideUdfInteger property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "OverrideUdfInteger", nillable = true)
    var overrideUdfInteger: Integer
    /**
     * Gets the value of the overrideUdfNumber property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the overrideUdfNumber property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "OverrideUdfNumber", nillable = true)
    var overrideUdfNumber: Double
    /**
     * Gets the value of the overrideUdfStartDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the overrideUdfStartDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "OverrideUdfStartDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var overrideUdfStartDate: Date
    /**
     * Gets the value of the overrideUdfText property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the overrideUdfText property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "OverrideUdfText")
    var overrideUdfText: String
    /**
     * Gets the value of the pendingUDFRAGType property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the pendingUDFRAGType property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PendingUDFRAGType")
    var pendingUDFRAGType: String
    /**
     * Gets the value of the pendingUdfCodeId property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the pendingUdfCodeId property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "PendingUdfCodeId", nillable = true)
    var pendingUdfCodeId: Double
    /**
     * Gets the value of the pendingUdfCost property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the pendingUdfCost property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "PendingUdfCost", nillable = true)
    var pendingUdfCost: Double
    /**
     * Gets the value of the pendingUdfEndDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the pendingUdfEndDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PendingUdfEndDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var pendingUdfEndDate: Date
    /**
     * Gets the value of the pendingUdfInteger property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the pendingUdfInteger property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "PendingUdfInteger", nillable = true)
    var pendingUdfInteger: Integer
    /**
     * Gets the value of the pendingUdfNumber property.
     *
     * @return
     * possible object is
     * [Double]
     */
    /**
     * Sets the value of the pendingUdfNumber property.
     *
     * @param value
     * allowed object is
     * [Double]
     */
    @XmlElement(name = "PendingUdfNumber", nillable = true)
    var pendingUdfNumber: Double
    /**
     * Gets the value of the pendingUdfStartDate property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the pendingUdfStartDate property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PendingUdfStartDate", type = String::class, nillable = true)
    @XmlJavaTypeAdapter(Adapter1::class)
    @XmlSchemaType(name = "dateTime")
    var pendingUdfStartDate: Date
    /**
     * Gets the value of the pendingUdfText property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the pendingUdfText property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PendingUdfText")
    var pendingUdfText: String
    /**
     * Gets the value of the projectObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the projectObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "ProjectObjectId")
    var projectObjectId: Integer
    /**
     * Gets the value of the requestUserObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the requestUserObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "RequestUserObjectId", nillable = true)
    var requestUserObjectId: Integer
    /**
     * Gets the value of the status property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the status property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "Status")
    var status: String
    /**
     * Gets the value of the udfDataType property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the udfDataType property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "UDFDataType")
    var udfDataType: String
    /**
     * Gets the value of the udfTypeObjectId property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the udfTypeObjectId property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlElement(name = "UDFTypeObjectId")
    var udfTypeObjectId: Integer

}
