//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.12.28 at 05:49:44 PM GMT
//

package net.sf.mpxj.ganttproject.schema

import java.util.ArrayList
import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlType

/**
 *
 * Java class for day-types complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="day-types">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="day-type" type="{}day-type" maxOccurs="unbounded" minOccurs="0"/>
 * &lt;element name="default-week" type="{}default-week"/>
 * &lt;element name="only-show-weekends" type="{}only-show-weekends"/>
 * &lt;element name="overriden-day-types" type="{http://www.w3.org/2001/XMLSchema}string"/>
 * &lt;element name="days" type="{http://www.w3.org/2001/XMLSchema}string"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "day-types", propOrder = {
    "dayType",
    "defaultWeek",
    "onlyShowWeekends",
    "overridenDayTypes",
    "days"
})
class DayTypes {

    @XmlElement(name = "day-type")
    protected var dayType: List<DayType>? = null
    /**
     * Gets the value of the defaultWeek property.
     *
     * @return
     * possible object is
     * [DefaultWeek]
     */
    /**
     * Sets the value of the defaultWeek property.
     *
     * @param value
     * allowed object is
     * [DefaultWeek]
     */
    @XmlElement(name = "default-week", required = true)
    var defaultWeek: DefaultWeek
    /**
     * Gets the value of the onlyShowWeekends property.
     *
     * @return
     * possible object is
     * [OnlyShowWeekends]
     */
    /**
     * Sets the value of the onlyShowWeekends property.
     *
     * @param value
     * allowed object is
     * [OnlyShowWeekends]
     */
    @XmlElement(name = "only-show-weekends", required = true)
    var onlyShowWeekends: OnlyShowWeekends
    /**
     * Gets the value of the overridenDayTypes property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the overridenDayTypes property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "overriden-day-types", required = true)
    var overridenDayTypes: String
    /**
     * Gets the value of the days property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the days property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(required = true)
    var days: String

    /**
     * Gets the value of the dayType property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dayType property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getDayType().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [DayType]
     *
     *
     */
    fun getDayType(): List<DayType> {
        if (dayType == null) {
            dayType = ArrayList<DayType>()
        }
        return this.dayType
    }

}
