//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.12.28 at 05:49:44 PM GMT
//

package net.sf.mpxj.ganttproject.schema

import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlAttribute
import javax.xml.bind.annotation.XmlType
import javax.xml.bind.annotation.XmlValue

/**
 *
 * Java class for depend complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="depend">
 * &lt;simpleContent>
 * &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 * &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 * &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}int" />
 * &lt;attribute name="difference" type="{http://www.w3.org/2001/XMLSchema}int" />
 * &lt;attribute name="hardness" type="{http://www.w3.org/2001/XMLSchema}string" />
 * &lt;/extension>
 * &lt;/simpleContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@SuppressWarnings("all")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "depend", propOrder = {
    "value"
})
class Depend {

    /**
     * Gets the value of the value property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the value property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlValue
    var value: String
    /**
     * Gets the value of the id property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the id property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlAttribute(name = "id")
    var id: Integer
    /**
     * Gets the value of the type property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the type property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlAttribute(name = "type")
    var type: Integer
    /**
     * Gets the value of the difference property.
     *
     * @return
     * possible object is
     * [Integer]
     */
    /**
     * Sets the value of the difference property.
     *
     * @param value
     * allowed object is
     * [Integer]
     */
    @XmlAttribute(name = "difference")
    var difference: Integer
    /**
     * Gets the value of the hardness property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the hardness property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "hardness")
    var hardness: String

}
