//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.08.02 at 09:18:52 PM BST
//

package net.sf.mpxj.planner.schema

import java.util.ArrayList
import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlAttribute
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlRootElement
import javax.xml.bind.annotation.XmlType
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter

/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "properties",
    "phases",
    "calendars",
    "tasks",
    "resourceGroups",
    "resources",
    "allocations"
})
@XmlRootElement(name = "project")
class Project {

    /**
     * Gets the value of the mrprojectVersion property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the mrprojectVersion property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "mrproject-version", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter::class)
    var mrprojectVersion: String
    /**
     * Gets the value of the name property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the name property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter::class)
    var name: String
    /**
     * Gets the value of the company property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the company property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute
    @XmlJavaTypeAdapter(NormalizedStringAdapter::class)
    var company: String
    /**
     * Gets the value of the manager property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the manager property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute
    @XmlJavaTypeAdapter(NormalizedStringAdapter::class)
    var manager: String
    /**
     * Gets the value of the projectStart property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the projectStart property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute(name = "project-start", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter::class)
    var projectStart: String
    /**
     * Gets the value of the calendar property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the calendar property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute
    @XmlJavaTypeAdapter(NormalizedStringAdapter::class)
    var calendar: String
    /**
     * Gets the value of the phase property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the phase property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlAttribute
    @XmlJavaTypeAdapter(NormalizedStringAdapter::class)
    var phase: String
    protected var properties: List<Properties>? = null
    /**
     * Gets the value of the phases property.
     *
     * @return
     * possible object is
     * [Phases]
     */
    /**
     * Sets the value of the phases property.
     *
     * @param value
     * allowed object is
     * [Phases]
     */
    var phases: Phases
    /**
     * Gets the value of the calendars property.
     *
     * @return
     * possible object is
     * [Calendars]
     */
    /**
     * Sets the value of the calendars property.
     *
     * @param value
     * allowed object is
     * [Calendars]
     */
    var calendars: Calendars
    /**
     * Gets the value of the tasks property.
     *
     * @return
     * possible object is
     * [Tasks]
     */
    /**
     * Sets the value of the tasks property.
     *
     * @param value
     * allowed object is
     * [Tasks]
     */
    var tasks: Tasks
    /**
     * Gets the value of the resourceGroups property.
     *
     * @return
     * possible object is
     * [ResourceGroups]
     */
    /**
     * Sets the value of the resourceGroups property.
     *
     * @param value
     * allowed object is
     * [ResourceGroups]
     */
    @XmlElement(name = "resource-groups")
    var resourceGroups: ResourceGroups
    /**
     * Gets the value of the resources property.
     *
     * @return
     * possible object is
     * [Resources]
     */
    /**
     * Sets the value of the resources property.
     *
     * @param value
     * allowed object is
     * [Resources]
     */
    var resources: Resources
    /**
     * Gets the value of the allocations property.
     *
     * @return
     * possible object is
     * [Allocations]
     */
    /**
     * Sets the value of the allocations property.
     *
     * @param value
     * allowed object is
     * [Allocations]
     */
    var allocations: Allocations

    /**
     * Gets the value of the properties property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the properties property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getProperties().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [Properties]
     *
     *
     */
    fun getProperties(): List<Properties> {
        if (properties == null) {
            properties = ArrayList<Properties>()
        }
        return this.properties
    }

}
