//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.01.18 at 11:10:40 AM GMT
//

package net.sf.mpxj.mspdi.schema

import javax.xml.bind.annotation.XmlRegistry

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the net.sf.mpxj.mspdi.schema package.
 *
 * An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
/**
 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.sf.mpxj.mspdi.schema
 *
 */
@XmlRegistry
class ObjectFactory {

    /**
     * Create an instance of [Project]
     *
     */
    fun createProject(): Project {
        return Project()
    }

    /**
     * Create an instance of [Project.Assignments]
     *
     */
    fun createProjectAssignments(): Project.Assignments {
        return Project.Assignments()
    }

    /**
     * Create an instance of [Project.Assignments.Assignment]
     *
     */
    fun createProjectAssignmentsAssignment(): Project.Assignments.Assignment {
        return Project.Assignments.Assignment()
    }

    /**
     * Create an instance of [Project.Resources]
     *
     */
    fun createProjectResources(): Project.Resources {
        return Project.Resources()
    }

    /**
     * Create an instance of [Project.Resources.Resource]
     *
     */
    fun createProjectResourcesResource(): Project.Resources.Resource {
        return Project.Resources.Resource()
    }

    /**
     * Create an instance of [Project.Resources.Resource.Rates]
     *
     */
    fun createProjectResourcesResourceRates(): Project.Resources.Resource.Rates {
        return Project.Resources.Resource.Rates()
    }

    /**
     * Create an instance of [Project.Resources.Resource.AvailabilityPeriods]
     *
     */
    fun createProjectResourcesResourceAvailabilityPeriods(): Project.Resources.Resource.AvailabilityPeriods {
        return Project.Resources.Resource.AvailabilityPeriods()
    }

    /**
     * Create an instance of [Project.Tasks]
     *
     */
    fun createProjectTasks(): Project.Tasks {
        return Project.Tasks()
    }

    /**
     * Create an instance of [Project.Tasks.Task]
     *
     */
    fun createProjectTasksTask(): Project.Tasks.Task {
        return Project.Tasks.Task()
    }

    /**
     * Create an instance of [Project.Calendars]
     *
     */
    fun createProjectCalendars(): Project.Calendars {
        return Project.Calendars()
    }

    /**
     * Create an instance of [Project.Calendars.Calendar]
     *
     */
    fun createProjectCalendarsCalendar(): Project.Calendars.Calendar {
        return Project.Calendars.Calendar()
    }

    /**
     * Create an instance of [Project.Calendars.Calendar.WorkWeeks]
     *
     */
    fun createProjectCalendarsCalendarWorkWeeks(): Project.Calendars.Calendar.WorkWeeks {
        return Project.Calendars.Calendar.WorkWeeks()
    }

    /**
     * Create an instance of [Project.Calendars.Calendar.WorkWeeks.WorkWeek]
     *
     */
    fun createProjectCalendarsCalendarWorkWeeksWorkWeek(): Project.Calendars.Calendar.WorkWeeks.WorkWeek {
        return Project.Calendars.Calendar.WorkWeeks.WorkWeek()
    }

    /**
     * Create an instance of [Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays]
     *
     */
    fun createProjectCalendarsCalendarWorkWeeksWorkWeekWeekDays(): Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays {
        return Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays()
    }

    /**
     * Create an instance of [Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays.WeekDay]
     *
     */
    fun createProjectCalendarsCalendarWorkWeeksWorkWeekWeekDaysWeekDay(): Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays.WeekDay {
        return Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays.WeekDay()
    }

    /**
     * Create an instance of [Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays.WeekDay.WorkingTimes]
     *
     */
    fun createProjectCalendarsCalendarWorkWeeksWorkWeekWeekDaysWeekDayWorkingTimes(): Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays.WeekDay.WorkingTimes {
        return Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays.WeekDay.WorkingTimes()
    }

    /**
     * Create an instance of [Project.Calendars.Calendar.Exceptions]
     *
     */
    fun createProjectCalendarsCalendarExceptions(): Project.Calendars.Calendar.Exceptions {
        return Project.Calendars.Calendar.Exceptions()
    }

    /**
     * Create an instance of [Project.Calendars.Calendar.Exceptions.Exception]
     *
     */
    fun createProjectCalendarsCalendarExceptionsException(): Project.Calendars.Calendar.Exceptions.Exception {
        return Project.Calendars.Calendar.Exceptions.Exception()
    }

    /**
     * Create an instance of [Project.Calendars.Calendar.Exceptions.Exception.WorkingTimes]
     *
     */
    fun createProjectCalendarsCalendarExceptionsExceptionWorkingTimes(): Project.Calendars.Calendar.Exceptions.Exception.WorkingTimes {
        return Project.Calendars.Calendar.Exceptions.Exception.WorkingTimes()
    }

    /**
     * Create an instance of [Project.Calendars.Calendar.WeekDays]
     *
     */
    fun createProjectCalendarsCalendarWeekDays(): Project.Calendars.Calendar.WeekDays {
        return Project.Calendars.Calendar.WeekDays()
    }

    /**
     * Create an instance of [Project.Calendars.Calendar.WeekDays.WeekDay]
     *
     */
    fun createProjectCalendarsCalendarWeekDaysWeekDay(): Project.Calendars.Calendar.WeekDays.WeekDay {
        return Project.Calendars.Calendar.WeekDays.WeekDay()
    }

    /**
     * Create an instance of [Project.Calendars.Calendar.WeekDays.WeekDay.WorkingTimes]
     *
     */
    fun createProjectCalendarsCalendarWeekDaysWeekDayWorkingTimes(): Project.Calendars.Calendar.WeekDays.WeekDay.WorkingTimes {
        return Project.Calendars.Calendar.WeekDays.WeekDay.WorkingTimes()
    }

    /**
     * Create an instance of [Project.ExtendedAttributes]
     *
     */
    fun createProjectExtendedAttributes(): Project.ExtendedAttributes {
        return Project.ExtendedAttributes()
    }

    /**
     * Create an instance of [Project.ExtendedAttributes.ExtendedAttribute]
     *
     */
    fun createProjectExtendedAttributesExtendedAttribute(): Project.ExtendedAttributes.ExtendedAttribute {
        return Project.ExtendedAttributes.ExtendedAttribute()
    }

    /**
     * Create an instance of [Project.ExtendedAttributes.ExtendedAttribute.ValueList]
     *
     */
    fun createProjectExtendedAttributesExtendedAttributeValueList(): Project.ExtendedAttributes.ExtendedAttribute.ValueList {
        return Project.ExtendedAttributes.ExtendedAttribute.ValueList()
    }

    /**
     * Create an instance of [Project.WBSMasks]
     *
     */
    fun createProjectWBSMasks(): Project.WBSMasks {
        return Project.WBSMasks()
    }

    /**
     * Create an instance of [Project.OutlineCodes]
     *
     */
    fun createProjectOutlineCodes(): Project.OutlineCodes {
        return Project.OutlineCodes()
    }

    /**
     * Create an instance of [Project.OutlineCodes.OutlineCode]
     *
     */
    fun createProjectOutlineCodesOutlineCode(): Project.OutlineCodes.OutlineCode {
        return Project.OutlineCodes.OutlineCode()
    }

    /**
     * Create an instance of [Project.OutlineCodes.OutlineCode.Masks]
     *
     */
    fun createProjectOutlineCodesOutlineCodeMasks(): Project.OutlineCodes.OutlineCode.Masks {
        return Project.OutlineCodes.OutlineCode.Masks()
    }

    /**
     * Create an instance of [Project.OutlineCodes.OutlineCode.Values]
     *
     */
    fun createProjectOutlineCodesOutlineCodeValues(): Project.OutlineCodes.OutlineCode.Values {
        return Project.OutlineCodes.OutlineCode.Values()
    }

    /**
     * Create an instance of [TimephasedDataType]
     *
     */
    fun createTimephasedDataType(): TimephasedDataType {
        return TimephasedDataType()
    }

    /**
     * Create an instance of [Project.Assignments.Assignment.ExtendedAttribute]
     *
     */
    fun createProjectAssignmentsAssignmentExtendedAttribute(): Project.Assignments.Assignment.ExtendedAttribute {
        return Project.Assignments.Assignment.ExtendedAttribute()
    }

    /**
     * Create an instance of [Project.Assignments.Assignment.Baseline]
     *
     */
    fun createProjectAssignmentsAssignmentBaseline(): Project.Assignments.Assignment.Baseline {
        return Project.Assignments.Assignment.Baseline()
    }

    /**
     * Create an instance of [Project.Resources.Resource.ExtendedAttribute]
     *
     */
    fun createProjectResourcesResourceExtendedAttribute(): Project.Resources.Resource.ExtendedAttribute {
        return Project.Resources.Resource.ExtendedAttribute()
    }

    /**
     * Create an instance of [Project.Resources.Resource.Baseline]
     *
     */
    fun createProjectResourcesResourceBaseline(): Project.Resources.Resource.Baseline {
        return Project.Resources.Resource.Baseline()
    }

    /**
     * Create an instance of [Project.Resources.Resource.OutlineCode]
     *
     */
    fun createProjectResourcesResourceOutlineCode(): Project.Resources.Resource.OutlineCode {
        return Project.Resources.Resource.OutlineCode()
    }

    /**
     * Create an instance of [Project.Resources.Resource.Rates.Rate]
     *
     */
    fun createProjectResourcesResourceRatesRate(): Project.Resources.Resource.Rates.Rate {
        return Project.Resources.Resource.Rates.Rate()
    }

    /**
     * Create an instance of [Project.Resources.Resource.AvailabilityPeriods.AvailabilityPeriod]
     *
     */
    fun createProjectResourcesResourceAvailabilityPeriodsAvailabilityPeriod(): Project.Resources.Resource.AvailabilityPeriods.AvailabilityPeriod {
        return Project.Resources.Resource.AvailabilityPeriods.AvailabilityPeriod()
    }

    /**
     * Create an instance of [Project.Tasks.Task.PredecessorLink]
     *
     */
    fun createProjectTasksTaskPredecessorLink(): Project.Tasks.Task.PredecessorLink {
        return Project.Tasks.Task.PredecessorLink()
    }

    /**
     * Create an instance of [Project.Tasks.Task.ExtendedAttribute]
     *
     */
    fun createProjectTasksTaskExtendedAttribute(): Project.Tasks.Task.ExtendedAttribute {
        return Project.Tasks.Task.ExtendedAttribute()
    }

    /**
     * Create an instance of [Project.Tasks.Task.Baseline]
     *
     */
    fun createProjectTasksTaskBaseline(): Project.Tasks.Task.Baseline {
        return Project.Tasks.Task.Baseline()
    }

    /**
     * Create an instance of [Project.Tasks.Task.OutlineCode]
     *
     */
    fun createProjectTasksTaskOutlineCode(): Project.Tasks.Task.OutlineCode {
        return Project.Tasks.Task.OutlineCode()
    }

    /**
     * Create an instance of [Project.Calendars.Calendar.WorkWeeks.WorkWeek.TimePeriod]
     *
     */
    fun createProjectCalendarsCalendarWorkWeeksWorkWeekTimePeriod(): Project.Calendars.Calendar.WorkWeeks.WorkWeek.TimePeriod {
        return Project.Calendars.Calendar.WorkWeeks.WorkWeek.TimePeriod()
    }

    /**
     * Create an instance of [Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays.WeekDay.WorkingTimes.WorkingTime]
     *
     */
    fun createProjectCalendarsCalendarWorkWeeksWorkWeekWeekDaysWeekDayWorkingTimesWorkingTime(): Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays.WeekDay.WorkingTimes.WorkingTime {
        return Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays.WeekDay.WorkingTimes.WorkingTime()
    }

    /**
     * Create an instance of [Project.Calendars.Calendar.Exceptions.Exception.TimePeriod]
     *
     */
    fun createProjectCalendarsCalendarExceptionsExceptionTimePeriod(): Project.Calendars.Calendar.Exceptions.Exception.TimePeriod {
        return Project.Calendars.Calendar.Exceptions.Exception.TimePeriod()
    }

    /**
     * Create an instance of [Project.Calendars.Calendar.Exceptions.Exception.WorkingTimes.WorkingTime]
     *
     */
    fun createProjectCalendarsCalendarExceptionsExceptionWorkingTimesWorkingTime(): Project.Calendars.Calendar.Exceptions.Exception.WorkingTimes.WorkingTime {
        return Project.Calendars.Calendar.Exceptions.Exception.WorkingTimes.WorkingTime()
    }

    /**
     * Create an instance of [Project.Calendars.Calendar.WeekDays.WeekDay.TimePeriod]
     *
     */
    fun createProjectCalendarsCalendarWeekDaysWeekDayTimePeriod(): Project.Calendars.Calendar.WeekDays.WeekDay.TimePeriod {
        return Project.Calendars.Calendar.WeekDays.WeekDay.TimePeriod()
    }

    /**
     * Create an instance of [Project.Calendars.Calendar.WeekDays.WeekDay.WorkingTimes.WorkingTime]
     *
     */
    fun createProjectCalendarsCalendarWeekDaysWeekDayWorkingTimesWorkingTime(): Project.Calendars.Calendar.WeekDays.WeekDay.WorkingTimes.WorkingTime {
        return Project.Calendars.Calendar.WeekDays.WeekDay.WorkingTimes.WorkingTime()
    }

    /**
     * Create an instance of [Project.ExtendedAttributes.ExtendedAttribute.ValueList.Value]
     *
     */
    fun createProjectExtendedAttributesExtendedAttributeValueListValue(): Project.ExtendedAttributes.ExtendedAttribute.ValueList.Value {
        return Project.ExtendedAttributes.ExtendedAttribute.ValueList.Value()
    }

    /**
     * Create an instance of [Project.WBSMasks.WBSMask]
     *
     */
    fun createProjectWBSMasksWBSMask(): Project.WBSMasks.WBSMask {
        return Project.WBSMasks.WBSMask()
    }

    /**
     * Create an instance of [Project.OutlineCodes.OutlineCode.Masks.Mask]
     *
     */
    fun createProjectOutlineCodesOutlineCodeMasksMask(): Project.OutlineCodes.OutlineCode.Masks.Mask {
        return Project.OutlineCodes.OutlineCode.Masks.Mask()
    }

    /**
     * Create an instance of [Project.OutlineCodes.OutlineCode.Values.Value]
     *
     */
    fun createProjectOutlineCodesOutlineCodeValuesValue(): Project.OutlineCodes.OutlineCode.Values.Value {
        return Project.OutlineCodes.OutlineCode.Values.Value()
    }

}
