//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.10 at 09:33:54 PM GMT
//

package net.sf.mpxj.ganttdesigner.schema

import javax.xml.bind.annotation.adapters.XmlAdapter
import net.sf.mpxj.Day

class Adapter5 : XmlAdapter<String, Day>() {

    @Override
    fun unmarshal(value: String): Day {
        return net.sf.mpxj.ganttdesigner.DatatypeConverter.parseDay(value)
    }

    @Override
    fun marshal(value: Day): String {
        return net.sf.mpxj.ganttdesigner.DatatypeConverter.printDay(value)
    }

}
