//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.10 at 09:33:54 PM GMT
//

package net.sf.mpxj.ganttdesigner.schema

import java.util.ArrayList
import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlAttribute
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlType
import javax.xml.bind.annotation.XmlValue

/**
 *
 * Java class for ganttDesignerRemark complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ganttDesignerRemark">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="Task" maxOccurs="unbounded">
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;attribute name="Row" type="{http://www.w3.org/2001/XMLSchema}int" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * &lt;/element>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ganttDesignerRemark", propOrder = {
    "task"
})
class GanttDesignerRemark {

    @XmlElement(name = "Task", required = true)
    protected var task: List<GanttDesignerRemark.Task>? = null

    /**
     * Gets the value of the task property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the task property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getTask().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [GanttDesignerRemark.Task]
     *
     *
     */
    fun getTask(): List<GanttDesignerRemark.Task> {
        if (task == null) {
            task = ArrayList<GanttDesignerRemark.Task>()
        }
        return this.task
    }

    /**
     *
     * Java class for anonymous complex type.
     *
     *
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     * &lt;complexContent>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     * &lt;attribute name="Row" type="{http://www.w3.org/2001/XMLSchema}int" />
     * &lt;/restriction>
     * &lt;/complexContent>
     * &lt;/complexType>
    </pre> *
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    class Task {

        /**
         * Gets the value of the content property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the content property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlValue
        var content: String
        /**
         * Gets the value of the row property.
         *
         * @return
         * possible object is
         * [Integer]
         */
        /**
         * Sets the value of the row property.
         *
         * @param value
         * allowed object is
         * [Integer]
         */
        @XmlAttribute(name = "Row")
        var row: Integer

    }

}
