//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.12 at 04:42:45 PM BST 
//

package net.sf.mpxj.conceptdraw.schema

import java.math.BigDecimal
import java.util.ArrayList
import java.util.Date
import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlSchemaType
import javax.xml.bind.annotation.XmlType
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter
import net.sf.mpxj.Priority

/**
 *
 * Java class for PPVItemsType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PPVItemsType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="PPVItem" maxOccurs="unbounded">
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="CompleteJournal" minOccurs="0">
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="CompleteJournalEntry" maxOccurs="unbounded" minOccurs="0">
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 * &lt;element name="Complete" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * &lt;/element>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * &lt;/element>
 * &lt;choice>
 * &lt;element name="ProjectID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 * &lt;sequence>
 * &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 * &lt;group ref="{http://www.schemas.conceptdraw.com/cdprj/document.xsd}ProjectProps"/>
 * &lt;element name="CompleteJournalTrackingPeriod" type="{http://www.schemas.conceptdraw.com/cdprj/document.xsd}LongTimeUnitType"/>
 * &lt;element ref="{http://www.schemas.conceptdraw.com/cdprj/document.xsd}Callouts" minOccurs="0"/>
 * &lt;element name="PPVItems" type="{http://www.schemas.conceptdraw.com/cdprj/document.xsd}PPVItemsType"/>
 * &lt;/sequence>
 * &lt;/choice>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * &lt;/element>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PPVItemsType", propOrder = {
    "ppvItem"
})
class PPVItemsType {

    @XmlElement(name = "PPVItem", required = true)
    protected var ppvItem: List<PPVItemsType.PPVItem>? = null

    /**
     * Gets the value of the ppvItem property.
     *
     *
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ppvItem property.
     *
     *
     *
     * For example, to add a new item, do as follows:
     * <pre>
     * getPPVItem().add(newItem);
    </pre> *
     *
     *
     *
     *
     * Objects of the following type(s) are allowed in the list
     * [PPVItemsType.PPVItem]
     *
     *
     */
    fun getPPVItem(): List<PPVItemsType.PPVItem> {
        if (ppvItem == null) {
            ppvItem = ArrayList<PPVItemsType.PPVItem>()
        }
        return this.ppvItem
    }

    /**
     *
     * Java class for anonymous complex type.
     *
     *
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     * &lt;complexContent>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     * &lt;sequence>
     * &lt;element name="CompleteJournal" minOccurs="0">
     * &lt;complexType>
     * &lt;complexContent>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     * &lt;sequence>
     * &lt;element name="CompleteJournalEntry" maxOccurs="unbounded" minOccurs="0">
     * &lt;complexType>
     * &lt;complexContent>
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     * &lt;sequence>
     * &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
     * &lt;element name="Complete" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     * &lt;/sequence>
     * &lt;/restriction>
     * &lt;/complexContent>
     * &lt;/complexType>
     * &lt;/element>
     * &lt;/sequence>
     * &lt;/restriction>
     * &lt;/complexContent>
     * &lt;/complexType>
     * &lt;/element>
     * &lt;choice>
     * &lt;element name="ProjectID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     * &lt;sequence>
     * &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     * &lt;group ref="{http://www.schemas.conceptdraw.com/cdprj/document.xsd}ProjectProps"/>
     * &lt;element name="CompleteJournalTrackingPeriod" type="{http://www.schemas.conceptdraw.com/cdprj/document.xsd}LongTimeUnitType"/>
     * &lt;element ref="{http://www.schemas.conceptdraw.com/cdprj/document.xsd}Callouts" minOccurs="0"/>
     * &lt;element name="PPVItems" type="{http://www.schemas.conceptdraw.com/cdprj/document.xsd}PPVItemsType"/>
     * &lt;/sequence>
     * &lt;/choice>
     * &lt;/sequence>
     * &lt;/restriction>
     * &lt;/complexContent>
     * &lt;/complexType>
    </pre> *
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "completeJournal",
        "projectID",
        "id",
        "name",
        "author",
        "company",
        "startDate",
        "finishDate",
        "budget",
        "goal",
        "site",
        "note",
        "baselineCost",
        "baselineStartDate",
        "baselineFinishDate",
        "showSubtasks",
        "priority",
        "isVisibleSubitems",
        "styleProject",
        "markerID",
        "hyperlinks",
        "completeJournalTrackingPeriod",
        "callouts",
        "ppvItems"
    })
    class PPVItem {

        /**
         * Gets the value of the completeJournal property.
         *
         * @return
         * possible object is
         * [PPVItemsType.PPVItem.CompleteJournal]
         */
        /**
         * Sets the value of the completeJournal property.
         *
         * @param value
         * allowed object is
         * [PPVItemsType.PPVItem.CompleteJournal]
         */
        @XmlElement(name = "CompleteJournal")
        var completeJournal: PPVItemsType.PPVItem.CompleteJournal
        /**
         * Gets the value of the projectID property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the projectID property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(name = "ProjectID", type = String::class)
        @XmlJavaTypeAdapter(Adapter5::class)
        @XmlSchemaType(name = "int")
        var projectID: Integer
        /**
         * Gets the value of the id property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the id property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(name = "ID", type = String::class)
        @XmlJavaTypeAdapter(Adapter5::class)
        @XmlSchemaType(name = "int")
        var id: Integer
        /**
         * Gets the value of the name property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the name property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(name = "Name")
        var name: String
        /**
         * Gets the value of the author property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the author property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(name = "Author")
        var author: String
        /**
         * Gets the value of the company property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the company property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(name = "Company")
        var company: String
        /**
         * Gets the value of the startDate property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the startDate property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(name = "StartDate", type = String::class)
        @XmlJavaTypeAdapter(Adapter1::class)
        @XmlSchemaType(name = "dateTime")
        var startDate: Date
        /**
         * Gets the value of the finishDate property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the finishDate property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(name = "FinishDate", type = String::class)
        @XmlJavaTypeAdapter(Adapter1::class)
        @XmlSchemaType(name = "dateTime")
        var finishDate: Date
        /**
         * Gets the value of the budget property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the budget property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(name = "Budget", type = String::class)
        @XmlJavaTypeAdapter(Adapter4::class)
        @XmlSchemaType(name = "double")
        var budget: Double
        /**
         * Gets the value of the goal property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the goal property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(name = "Goal")
        var goal: String
        /**
         * Gets the value of the site property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the site property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(name = "Site")
        var site: String
        /**
         * Gets the value of the note property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the note property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(name = "Note")
        var note: String
        /**
         * Gets the value of the baselineCost property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the baselineCost property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(name = "BaselineCost", type = String::class)
        @XmlJavaTypeAdapter(Adapter4::class)
        @XmlSchemaType(name = "double")
        var baselineCost: Double
        /**
         * Gets the value of the baselineStartDate property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the baselineStartDate property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(name = "BaselineStartDate", type = String::class)
        @XmlJavaTypeAdapter(Adapter1::class)
        @XmlSchemaType(name = "dateTime")
        var baselineStartDate: Date
        /**
         * Gets the value of the baselineFinishDate property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the baselineFinishDate property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(name = "BaselineFinishDate", type = String::class)
        @XmlJavaTypeAdapter(Adapter1::class)
        @XmlSchemaType(name = "dateTime")
        var baselineFinishDate: Date
        /**
         * Gets the value of the showSubtasks property.
         *
         * @return
         * possible object is
         * [Boolean]
         */
        /**
         * Sets the value of the showSubtasks property.
         *
         * @param value
         * allowed object is
         * [Boolean]
         */
        @XmlElement(name = "ShowSubtasks")
        var isShowSubtasks: Boolean
        /**
         * The priority of the project.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the priority property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(name = "Priority", type = String::class)
        @XmlJavaTypeAdapter(Adapter7::class)
        var priority: Priority
        /**
         * Gets the value of the isVisibleSubitems property.
         *
         * @return
         * possible object is
         * [Boolean]
         */
        /**
         * Sets the value of the isVisibleSubitems property.
         *
         * @param value
         * allowed object is
         * [Boolean]
         */
        @XmlElement(name = "IsVisibleSubitems")
        var isIsVisibleSubitems: Boolean
        /**
         * Gets the value of the styleProject property.
         *
         * @return
         * possible object is
         * [StyleProject]
         */
        /**
         * Sets the value of the styleProject property.
         *
         * @param value
         * allowed object is
         * [StyleProject]
         */
        @XmlElement(name = "StyleProject")
        var styleProject: StyleProject
        /**
         * Gets the value of the markerID property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the markerID property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(name = "MarkerID", type = String::class)
        @XmlJavaTypeAdapter(Adapter5::class)
        @XmlSchemaType(name = "int")
        var markerID: Integer
        /**
         * Hyperlinks associated with the project.
         *
         * @return
         * possible object is
         * [Hyperlinks]
         */
        /**
         * Sets the value of the hyperlinks property.
         *
         * @param value
         * allowed object is
         * [Hyperlinks]
         */
        @XmlElement(name = "Hyperlinks")
        var hyperlinks: Hyperlinks
        /**
         * Gets the value of the completeJournalTrackingPeriod property.
         *
         * @return
         * possible object is
         * [String]
         */
        /**
         * Sets the value of the completeJournalTrackingPeriod property.
         *
         * @param value
         * allowed object is
         * [String]
         */
        @XmlElement(name = "CompleteJournalTrackingPeriod", type = String::class)
        @XmlJavaTypeAdapter(Adapter5::class)
        @XmlSchemaType(name = "int")
        var completeJournalTrackingPeriod: Integer
        /**
         * Gets the value of the callouts property.
         *
         * @return
         * possible object is
         * [Callouts]
         */
        /**
         * Sets the value of the callouts property.
         *
         * @param value
         * allowed object is
         * [Callouts]
         */
        @XmlElement(name = "Callouts")
        var callouts: Callouts
        /**
         * Gets the value of the ppvItems property.
         *
         * @return
         * possible object is
         * [PPVItemsType]
         */
        /**
         * Sets the value of the ppvItems property.
         *
         * @param value
         * allowed object is
         * [PPVItemsType]
         */
        @XmlElement(name = "PPVItems")
        var ppvItems: PPVItemsType

        /**
         *
         * Java class for anonymous complex type.
         *
         *
         * The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         * &lt;complexContent>
         * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         * &lt;sequence>
         * &lt;element name="CompleteJournalEntry" maxOccurs="unbounded" minOccurs="0">
         * &lt;complexType>
         * &lt;complexContent>
         * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         * &lt;sequence>
         * &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
         * &lt;element name="Complete" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         * &lt;/sequence>
         * &lt;/restriction>
         * &lt;/complexContent>
         * &lt;/complexType>
         * &lt;/element>
         * &lt;/sequence>
         * &lt;/restriction>
         * &lt;/complexContent>
         * &lt;/complexType>
        </pre> *
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "completeJournalEntry"
        })
        class CompleteJournal {

            @XmlElement(name = "CompleteJournalEntry")
            protected var completeJournalEntry: List<PPVItemsType.PPVItem.CompleteJournal.CompleteJournalEntry>? = null

            /**
             * Gets the value of the completeJournalEntry property.
             *
             *
             *
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the completeJournalEntry property.
             *
             *
             *
             * For example, to add a new item, do as follows:
             * <pre>
             * getCompleteJournalEntry().add(newItem);
            </pre> *
             *
             *
             *
             *
             * Objects of the following type(s) are allowed in the list
             * [PPVItemsType.PPVItem.CompleteJournal.CompleteJournalEntry]
             *
             *
             */
            fun getCompleteJournalEntry(): List<PPVItemsType.PPVItem.CompleteJournal.CompleteJournalEntry> {
                if (completeJournalEntry == null) {
                    completeJournalEntry = ArrayList<PPVItemsType.PPVItem.CompleteJournal.CompleteJournalEntry>()
                }
                return this.completeJournalEntry
            }

            /**
             *
             * Java class for anonymous complex type.
             *
             *
             * The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             * &lt;complexContent>
             * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             * &lt;sequence>
             * &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
             * &lt;element name="Complete" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             * &lt;/sequence>
             * &lt;/restriction>
             * &lt;/complexContent>
             * &lt;/complexType>
            </pre> *
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "date",
                "complete"
            })
            class CompleteJournalEntry {

                /**
                 * Gets the value of the date property.
                 *
                 * @return
                 * possible object is
                 * [String]
                 */
                /**
                 * Sets the value of the date property.
                 *
                 * @param value
                 * allowed object is
                 * [String]
                 */
                @XmlElement(name = "Date", required = true, type = String::class)
                @XmlJavaTypeAdapter(Adapter2::class)
                @XmlSchemaType(name = "date")
                var date: Date
                /**
                 * Gets the value of the complete property.
                 *
                 * @return
                 * possible object is
                 * [BigDecimal]
                 */
                /**
                 * Sets the value of the complete property.
                 *
                 * @param value
                 * allowed object is
                 * [BigDecimal]
                 */
                @XmlElement(name = "Complete", required = true)
                var complete: BigDecimal

            }

        }

    }

}
