//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.12 at 04:42:45 PM BST 
//

package net.sf.mpxj.conceptdraw.schema

import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlRootElement
import javax.xml.bind.annotation.XmlSchemaType
import javax.xml.bind.annotation.XmlType
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter

/**
 *
 * Java class for anonymous complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="PrimaryUnits" type="{http://www.w3.org/2001/XMLSchema}int"/>
 * &lt;element name="PrimaryAlign" type="{http://www.w3.org/2001/XMLSchema}int"/>
 * &lt;element name="SecondaryUnits" type="{http://www.w3.org/2001/XMLSchema}int"/>
 * &lt;element name="SecondaryAlign" type="{http://www.w3.org/2001/XMLSchema}int"/>
 * &lt;element name="SecondaryCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
</pre> *
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "primaryUnits",
    "primaryAlign",
    "secondaryUnits",
    "secondaryAlign",
    "secondaryCount"
})
@XmlRootElement(name = "TimeScale")
class TimeScale {

    /**
     * Gets the value of the primaryUnits property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the primaryUnits property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PrimaryUnits", required = true, type = String::class)
    @XmlJavaTypeAdapter(Adapter5::class)
    @XmlSchemaType(name = "int")
    var primaryUnits: Integer
    /**
     * Gets the value of the primaryAlign property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the primaryAlign property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "PrimaryAlign", required = true, type = String::class)
    @XmlJavaTypeAdapter(Adapter5::class)
    @XmlSchemaType(name = "int")
    var primaryAlign: Integer
    /**
     * Gets the value of the secondaryUnits property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the secondaryUnits property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "SecondaryUnits", required = true, type = String::class)
    @XmlJavaTypeAdapter(Adapter5::class)
    @XmlSchemaType(name = "int")
    var secondaryUnits: Integer
    /**
     * Gets the value of the secondaryAlign property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the secondaryAlign property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "SecondaryAlign", required = true, type = String::class)
    @XmlJavaTypeAdapter(Adapter5::class)
    @XmlSchemaType(name = "int")
    var secondaryAlign: Integer
    /**
     * Gets the value of the secondaryCount property.
     *
     * @return
     * possible object is
     * [String]
     */
    /**
     * Sets the value of the secondaryCount property.
     *
     * @param value
     * allowed object is
     * [String]
     */
    @XmlElement(name = "SecondaryCount", required = true, type = String::class)
    @XmlJavaTypeAdapter(Adapter5::class)
    @XmlSchemaType(name = "int")
    var secondaryCount: Integer

}
